# 1. Import Libraries

In [1]:
import sys
from pathlib import Path

# Thêm thư mục gốc (project root) vào Python path
project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

import pandas as pd
import xgboost as xgb

from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, mean_absolute_percentage_error, root_mean_squared_error

import numpy as np

from utils.features import build_features

import optuna

# 2. Load Dataset

In [2]:
df_train, df_val = build_features(
                                df_train = pd.read_excel("../Dataset/training.xlsx"), 
                                df_test = None,
                                pls_fit_years = [1]
                                   )

In [4]:
features = [
    'Year', 'Month', 'Day', 'Hour',
    'Combined_Temp',
    'Combined_GHI_1', 'Combined_GHI_2'
]
target = 'Load'

# 3. Split Data

In [7]:
# Year 1 → TRAIN
train_mask = df_train['Year'] == 1

# Year 2 → VALIDATION
val_mask = df_val['Year'] == 2

# Year 3 → TEST
# Testing.xlsx is assumed to contain Year 3

X_train = df_train.loc[train_mask, features]
y_train = df_train.loc[train_mask, target]

X_val = df_val.loc[val_mask, features]
y_val = df_val.loc[val_mask, target]

print("Dataset sizes:")
print(f"Train (Year 1): {len(X_train):,}")
print(f"Validation (Year 2): {len(X_val):,}")

Dataset sizes:
Train (Year 1): 8,784
Validation (Year 2): 8,760

# 4. Train on year 1, evaluate on year 2

In [8]:
tscv = TimeSeriesSplit(n_splits=4)

In [9]:
def objective(trial):

    params = {
        "objective": "reg:squarederror",

        "n_estimators": trial.suggest_int(
            "n_estimators",
            100,
            1500
        ),

        "learning_rate": trial.suggest_float(
            "learning_rate",
            0.01,
            0.2,
            log=True
        ),

        "max_depth": trial.suggest_int(
            "max_depth",
            3,
            10
        ),

        "min_child_weight": trial.suggest_int(
            "min_child_weight",
            1,
            10
        ),

        "subsample": trial.suggest_float(
            "subsample",
            0.6,
            1.0
        ),

        "colsample_bytree": trial.suggest_float(
            "colsample_bytree",
            0.6,
            1.0
        ),

        "gamma": trial.suggest_float(
            "gamma",
            0,
            5
        ),

        "reg_alpha": trial.suggest_float(
            "reg_alpha",
            1e-8,
            10,
            log=True
        ),

        "reg_lambda": trial.suggest_float(
            "reg_lambda",
            1e-3,
            10,
            log=True
        ),

        "random_state": 42,
        "n_jobs": -1
    }

    fold_rmse = []

    # ============================================
    # Time-series CV trên YEAR 1
    # ============================================

    for train_idx, val_idx in tscv.split(X_train):

        X_fold_train = X_train.iloc[train_idx]
        X_fold_val = X_train.iloc[val_idx]

        y_fold_train = y_train.iloc[train_idx]
        y_fold_val = y_train.iloc[val_idx]

        model = xgb.XGBRegressor(**params)

        model.fit(
            X_fold_train,
            y_fold_train
        )

        y_pred = model.predict(
            X_fold_val
        )

        rmse = root_mean_squared_error(
            y_fold_val,
            y_pred
        )

        fold_rmse.append(rmse)

    # Optuna minimize mean CV RMSE
    return np.mean(fold_rmse)

In [10]:
study = optuna.create_study(
    direction="minimize",
    study_name="xgb_year1_timeseries_cv"
)

study.optimize(
    objective,
    n_trials=100,
    show_progress_bar=True
)

[I 2026-10-02 18:22:10,903] A new study created in memory with name: xgb_year1_timeseries_cv

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-10-02 18:22:13,110] Trial 0 finished with value: 315.3281440734863 and parameters: {'n_estimators': 792, 'learning_rate': 0.1739368002405972, 'max_depth': 8, 'min_child_weight': 9, 'subsample': 0.9875056549195667, 'colsample_bytree': 0.6497739720188765, 'gamma': 4.839028484332111, 'reg_alpha': 3.5136077434827067e-06, 'reg_lambda': 0.001652822117935116}. Best is trial 0 with value: 315.3281440734863.
[I 2026-10-02 18:22:15,628] Trial 1 finished with value: 305.4420356750488 and parameters: {'n_estimators': 982, 'learning_rate': 0.07820007940661113, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.8127533564499771, 'colsample_bytree': 0.7161935159625922, 'gamma': 1.1750073762573832, 'reg_alpha': 1.0471786591448385e-06, 'reg_lambda': 0.034933418655702556}. Best is trial 1 with value: 305.4420356750488.
[I 2026-10-02 18:22:17,363] Trial 2 finished with value: 301.45520782470703 and parameters: {'n_estimators': 907, 'learning_rate': 0.03557411148133636, 'max_depth': 6, 'min_child_weight': 7, 'subsample': 0.9061110478216062, 'colsample_bytree': 0.8281974783988268, 'gamma': 4.0585355517251, 'reg_alpha': 0.001109696897351887, 'reg_lambda': 1.2046281843352629}. Best is trial 2 with value: 301.45520782470703.
[I 2026-10-02 18:22:21,168] Trial 3 finished with value: 300.37557220458984 and parameters: {'n_estimators': 1043, 'learning_rate': 0.019723556283933522, 'max_depth': 9, 'min_child_weight': 7, 'subsample': 0.8228100225067283, 'colsample_bytree': 0.942425629787914, 'gamma': 0.25290429108332957, 'reg_alpha': 5.509304758914821e-08, 'reg_lambda': 0.24899922793717966}. Best is trial 3 with value: 300.37557220458984.
[I 2026-10-02 18:22:21,419] Trial 4 finished with value: 287.4553642272949 and parameters: {'n_estimators': 221, 'learning_rate': 0.038021288425579385, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.9463507736410943, 'colsample_bytree': 0.7213664610240951, 'gamma': 3.9725217241120063, 'reg_alpha': 0.7387711663644984, 'reg_lambda': 0.00306095103437392}. Best is trial 4 with value: 287.4553642272949.
[I 2026-10-02 18:22:22,266] Trial 5 finished with value: 295.2656936645508 and parameters: {'n_estimators': 407, 'learning_rate': 0.012605701677668288, 'max_depth': 6, 'min_child_weight': 6, 'subsample': 0.875949050718335, 'colsample_bytree': 0.7410569527734199, 'gamma': 4.854151284021016, 'reg_alpha': 0.0018527274562888786, 'reg_lambda': 0.3676108251693016}. Best is trial 4 with value: 287.4553642272949.
[I 2026-10-02 18:22:24,660] Trial 6 finished with value: 311.99424743652344 and parameters: {'n_estimators': 1310, 'learning_rate': 0.1784817190008299, 'max_depth': 6, 'min_child_weight': 10, 'subsample': 0.8714389339609925, 'colsample_bytree': 0.617104281578387, 'gamma': 1.922425011696749, 'reg_alpha': 1.6591807237361202e-05, 'reg_lambda': 1.1547392936187713}. Best is trial 4 with value: 287.4553642272949.
[I 2026-10-02 18:22:26,826] Trial 7 finished with value: 306.0511703491211 and parameters: {'n_estimators': 1191, 'learning_rate': 0.08383746593682939, 'max_depth': 6, 'min_child_weight': 9, 'subsample': 0.7027850511643234, 'colsample_bytree': 0.697327674276149, 'gamma': 4.445077724825436, 'reg_alpha': 0.0016206424334055394, 'reg_lambda': 7.983338550495529}. Best is trial 4 with value: 287.4553642272949.
[I 2026-10-02 18:22:27,561] Trial 8 finished with value: 302.38376235961914 and parameters: {'n_estimators': 493, 'learning_rate': 0.09533613060437711, 'max_depth': 5, 'min_child_weight': 7, 'subsample': 0.940899653006241, 'colsample_bytree': 0.6527430732325679, 'gamma': 1.685344117655141, 'reg_alpha': 3.1610908885383964e-05, 'reg_lambda': 0.5835546043380968}. Best is trial 4 with value: 287.4553642272949.
[I 2026-10-02 18:22:28,261] Trial 9 finished with value: 277.1603240966797 and parameters: {'n_estimators': 583, 'learning_rate': 0.05460575394747581, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.9018526735127371, 'colsample_bytree': 0.9986965599392653, 'gamma': 4.268164286965575, 'reg_alpha': 8.683178103829745e-08, 'reg_lambda': 0.0018965239194194676}. Best is trial 9 with value: 277.1603240966797.
[I 2026-10-02 18:22:29,318] Trial 10 finished with value: 293.96843338012695 and parameters: {'n_estimators': 831, 'learning_rate': 0.06572801157742199, 'max_depth': 4, 'min_child_weight': 7, 'subsample': 0.9526090034959298, 'colsample_bytree': 0.6342966811654989, 'gamma': 3.1119799660683523, 'reg_alpha': 2.3077089237385202e-07, 'reg_lambda': 0.0011540895479882683}. Best is trial 9 with value: 277.1603240966797.
[I 2026-10-02 18:22:29,847] Trial 11 finished with value: 281.3370246887207 and parameters: {'n_estimators': 466, 'learning_rate': 0.027158908675571053, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.9180304721814153, 'colsample_bytree': 0.7804384010807237, 'gamma': 3.4344819375272784, 'reg_alpha': 0.03888489014255421, 'reg_lambda': 0.0030309805837492533}. Best is trial 9 with value: 277.1603240966797.
[I 2026-10-02 18:22:30,401] Trial 12 finished with value: 276.4477195739746 and parameters: {'n_estimators': 451, 'learning_rate': 0.05902069446008568, 'max_depth': 3, 'min_child_weight': 10, 'subsample': 0.9292292794307074, 'colsample_bytree': 0.8580843427852525, 'gamma': 3.7331946772020443, 'reg_alpha': 0.0003628597960638142, 'reg_lambda': 0.0029097416029303064}. Best is trial 12 with value: 276.4477195739746.
[I 2026-10-02 18:22:31,081] Trial 13 finished with value: 280.8063316345215 and parameters: {'n_estimators': 621, 'learning_rate': 0.10419003079051033, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.9052366101438497, 'colsample_bytree': 0.9837003321925956, 'gamma': 4.936179770769193, 'reg_alpha': 0.0018414273312159987, 'reg_lambda': 0.004465095224039101}. Best is trial 12 with value: 276.4477195739746.
[I 2026-10-02 18:22:31,472] Trial 14 finished with value: 284.6657066345215 and parameters: {'n_estimators': 264, 'learning_rate': 0.05879327495778414, 'max_depth': 4, 'min_child_weight': 8, 'subsample': 0.8847932846805828, 'colsample_bytree': 0.8433215515148136, 'gamma': 3.155393401879622, 'reg_alpha': 3.437248517210539e-07, 'reg_lambda': 0.0019129929705112676}. Best is trial 12 with value: 276.4477195739746.
[I 2026-10-02 18:22:32,140] Trial 15 finished with value: 277.5651550292969 and parameters: {'n_estimators': 580, 'learning_rate': 0.06536981135865573, 'max_depth': 3, 'min_child_weight': 6, 'subsample': 0.9479190948725416, 'colsample_bytree': 0.9896518285149372, 'gamma': 4.337057832161969, 'reg_alpha': 4.191179736221308e-07, 'reg_lambda': 0.022591071416951117}. Best is trial 12 with value: 276.4477195739746.
[I 2026-10-02 18:22:32,460] Trial 16 finished with value: 279.02910232543945 and parameters: {'n_estimators': 287, 'learning_rate': 0.0703444115964753, 'max_depth': 3, 'min_child_weight': 9, 'subsample': 0.9130718237188494, 'colsample_bytree': 0.9241232205773346, 'gamma': 3.5531381062435776, 'reg_alpha': 0.02339116216882475, 'reg_lambda': 0.0016796310198339702}. Best is trial 12 with value: 276.4477195739746.
[I 2026-10-02 18:22:33,484] Trial 17 finished with value: 299.52952575683594 and parameters: {'n_estimators': 708, 'learning_rate': 0.07793433120993838, 'max_depth': 5, 'min_child_weight': 9, 'subsample': 0.9476989159405567, 'colsample_bytree': 0.8282809058637524, 'gamma': 3.7474317371431067, 'reg_alpha': 3.6197662865710996e-05, 'reg_lambda': 0.01359299374731341}. Best is trial 12 with value: 276.4477195739746.
[I 2026-10-02 18:22:34,688] Trial 18 finished with value: 291.9054145812988 and parameters: {'n_estimators': 955, 'learning_rate': 0.044745794363759965, 'max_depth': 4, 'min_child_weight': 7, 'subsample': 0.8473034719253935, 'colsample_bytree': 0.9809015888797913, 'gamma': 3.9180082226071313, 'reg_alpha': 7.977621777786336e-05, 'reg_lambda': 0.0035991009812279076}. Best is trial 12 with value: 276.4477195739746.
[I 2026-10-02 18:22:35,660] Trial 19 finished with value: 299.18236923217773 and parameters: {'n_estimators': 770, 'learning_rate': 0.07702393007966662, 'max_depth': 4, 'min_child_weight': 9, 'subsample': 0.9074323871831936, 'colsample_bytree': 0.9621541860157782, 'gamma': 4.356402661960654, 'reg_alpha': 2.386682995621218e-07, 'reg_lambda': 0.0014864527253125308}. Best is trial 12 with value: 276.4477195739746.
[I 2026-10-02 18:22:35,870] Trial 20 finished with value: 283.81576919555664 and parameters: {'n_estimators': 160, 'learning_rate': 0.08502682140898803, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.9357636844571751, 'colsample_bytree': 0.9643596026551366, 'gamma': 4.7083273759539255, 'reg_alpha': 7.093394420586901e-07, 'reg_lambda': 0.003134160372298564}. Best is trial 12 with value: 276.4477195739746.
[I 2026-10-02 18:22:36,375] Trial 21 finished with value: 290.8744316101074 and parameters: {'n_estimators': 363, 'learning_rate': 0.02506708538041517, 'max_depth': 3, 'min_child_weight': 10, 'subsample': 0.9679733674776025, 'colsample_bytree': 0.9995925658552424, 'gamma': 4.352853817590709, 'reg_alpha': 9.494335105696782e-06, 'reg_lambda': 0.005053237354112151}. Best is trial 12 with value: 276.4477195739746.
[I 2026-10-02 18:22:38,002] Trial 22 finished with value: 299.3573760986328 and parameters: {'n_estimators': 835, 'learning_rate': 0.0541217966719742, 'max_depth': 5, 'min_child_weight': 7, 'subsample': 0.8262055628188065, 'colsample_bytree': 0.8821107618379053, 'gamma': 3.8625395956300843, 'reg_alpha': 1.0603371424881034e-08, 'reg_lambda': 0.0029750859479263712}. Best is trial 12 with value: 276.4477195739746.
[I 2026-10-02 18:22:38,689] Trial 23 finished with value: 281.7241744995117 and parameters: {'n_estimators': 516, 'learning_rate': 0.09893167596195317, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.8553660748079385, 'colsample_bytree': 0.9335662689578209, 'gamma': 3.113207873806827, 'reg_alpha': 6.512122690224551e-08, 'reg_lambda': 0.006296109890958361}. Best is trial 12 with value: 276.4477195739746.
[I 2026-10-02 18:22:39,518] Trial 24 finished with value: 290.16269302368164 and parameters: {'n_estimators': 458, 'learning_rate': 0.04463927122012848, 'max_depth': 5, 'min_child_weight': 8, 'subsample': 0.9592414353139221, 'colsample_bytree': 0.9863969192445092, 'gamma': 3.6289330640098982, 'reg_alpha': 8.308275082444663e-07, 'reg_lambda': 0.012002495521263883}. Best is trial 12 with value: 276.4477195739746.
[I 2026-10-02 18:22:41,045] Trial 25 finished with value: 309.7502021789551 and parameters: {'n_estimators': 820, 'learning_rate': 0.09251327734730988, 'max_depth': 5, 'min_child_weight': 6, 'subsample': 0.9465614074164427, 'colsample_bytree': 0.9744839437299689, 'gamma': 3.8386106652057106, 'reg_alpha': 2.453263492326511e-08, 'reg_lambda': 0.004099043228500697}. Best is trial 12 with value: 276.4477195739746.
[I 2026-10-02 18:22:41,560] Trial 26 finished with value: 284.3255500793457 and parameters: {'n_estimators': 457, 'learning_rate': 0.032008969357338615, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.9572119418455403, 'colsample_bytree': 0.9693698569107082, 'gamma': 2.763857011567514, 'reg_alpha': 3.4910338908834933e-07, 'reg_lambda': 0.003270645719022142}. Best is trial 12 with value: 276.4477195739746.
[I 2026-10-02 18:22:42,102] Trial 27 finished with value: 277.1202583312988 and parameters: {'n_estimators': 363, 'learning_rate': 0.0644684922656888, 'max_depth': 3, 'min_child_weight': 6, 'subsample': 0.9434245431176899, 'colsample_bytree': 0.8677005320912681, 'gamma': 4.569037439956487, 'reg_alpha': 1.005124956846565e-05, 'reg_lambda': 0.007312593250268364}. Best is trial 12 with value: 276.4477195739746.
[I 2026-10-02 18:22:42,734] Trial 28 finished with value: 282.94532775878906 and parameters: {'n_estimators': 395, 'learning_rate': 0.07829531889915406, 'max_depth': 4, 'min_child_weight': 8, 'subsample': 0.8994218079414401, 'colsample_bytree': 0.9366901627093424, 'gamma': 4.398490363589766, 'reg_alpha': 7.137001391874802e-06, 'reg_lambda': 0.001083846840818855}. Best is trial 12 with value: 276.4477195739746.
[I 2026-10-02 18:22:43,644] Trial 29 finished with value: 294.0302429199219 and parameters: {'n_estimators': 625, 'learning_rate': 0.07519633785053566, 'max_depth': 4, 'min_child_weight': 8, 'subsample': 0.9244567906261287, 'colsample_bytree': 0.9293995346634153, 'gamma': 4.6479881163625985, 'reg_alpha': 1.2527968631924772e-08, 'reg_lambda': 0.029521479851619462}. Best is trial 12 with value: 276.4477195739746.
[I 2026-10-02 18:22:44,200] Trial 30 finished with value: 278.983943939209 and parameters: {'n_estimators': 457, 'learning_rate': 0.062182954243232176, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.8904362725537074, 'colsample_bytree': 0.9817003326220339, 'gamma': 4.000961841470335, 'reg_alpha': 1.515575332797924e-07, 'reg_lambda': 0.0016937959819280377}. Best is trial 12 with value: 276.4477195739746.
[I 2026-10-02 18:22:44,790] Trial 31 finished with value: 276.2749938964844 and parameters: {'n_estimators': 408, 'learning_rate': 0.10767259398767831, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.9677186745783506, 'colsample_bytree': 0.8757791767255453, 'gamma': 4.456261375749151, 'reg_alpha': 8.649955500652477e-08, 'reg_lambda': 0.008079664171671497}. Best is trial 31 with value: 276.2749938964844.
[I 2026-10-02 18:22:45,363] Trial 32 finished with value: 280.3559799194336 and parameters: {'n_estimators': 475, 'learning_rate': 0.057567793090794774, 'max_depth': 3, 'min_child_weight': 6, 'subsample': 0.9545737577303561, 'colsample_bytree': 0.8836335247211822, 'gamma': 4.082458632734231, 'reg_alpha': 9.60884677000536e-05, 'reg_lambda': 0.002849378298016241}. Best is trial 31 with value: 276.2749938964844.
[I 2026-10-02 18:22:45,660] Trial 33 finished with value: 280.1418762207031 and parameters: {'n_estimators': 211, 'learning_rate': 0.09511587283197494, 'max_depth': 3, 'min_child_weight': 6, 'subsample': 0.8880721431461039, 'colsample_bytree': 0.8517478862601184, 'gamma': 4.904714505870203, 'reg_alpha': 2.6801392984209283e-07, 'reg_lambda': 0.006692959389214356}. Best is trial 31 with value: 276.2749938964844.
[I 2026-10-02 18:22:46,272] Trial 34 finished with value: 274.699031829834 and parameters: {'n_estimators': 441, 'learning_rate': 0.05664404037733558, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.9425808349863602, 'colsample_bytree': 0.699179427363179, 'gamma': 4.482015199380389, 'reg_alpha': 3.162761314228344e-08, 'reg_lambda': 0.0035202824397456314}. Best is trial 34 with value: 274.699031829834.
[I 2026-10-02 18:22:46,798] Trial 35 finished with value: 293.21632385253906 and parameters: {'n_estimators': 462, 'learning_rate': 0.17676041894036496, 'max_depth': 3, 'min_child_weight': 9, 'subsample': 0.9371165120337759, 'colsample_bytree': 0.9257166021891743, 'gamma': 4.676964431421237, 'reg_alpha': 1.9753594700752954e-07, 'reg_lambda': 0.0174703799324925}. Best is trial 34 with value: 274.699031829834.
[I 2026-10-02 18:22:47,294] Trial 36 finished with value: 287.69960021972656 and parameters: {'n_estimators': 481, 'learning_rate': 0.14783149200404067, 'max_depth': 3, 'min_child_weight': 9, 'subsample': 0.9709270738935559, 'colsample_bytree': 0.9359003708123689, 'gamma': 4.8006930995954455, 'reg_alpha': 1.6847180837996727e-08, 'reg_lambda': 0.003921800435340988}. Best is trial 34 with value: 274.699031829834.
[I 2026-10-02 18:22:47,970] Trial 37 finished with value: 282.9817237854004 and parameters: {'n_estimators': 427, 'learning_rate': 0.055367968673200284, 'max_depth': 4, 'min_child_weight': 7, 'subsample': 0.9106301067119408, 'colsample_bytree': 0.7969149731220867, 'gamma': 4.474059573266041, 'reg_alpha': 1.398774946210723e-06, 'reg_lambda': 0.016651452524605363}. Best is trial 34 with value: 274.699031829834.
[I 2026-10-02 18:22:48,648] Trial 38 finished with value: 277.67543029785156 and parameters: {'n_estimators': 637, 'learning_rate': 0.08532724917072262, 'max_depth': 3, 'min_child_weight': 6, 'subsample': 0.9462046125121644, 'colsample_bytree': 0.9124241205503677, 'gamma': 4.0593355530235335, 'reg_alpha': 7.006289983801039e-08, 'reg_lambda': 0.014546978091525437}. Best is trial 34 with value: 274.699031829834.
[I 2026-10-02 18:22:49,182] Trial 39 finished with value: 280.32604598999023 and parameters: {'n_estimators': 344, 'learning_rate': 0.05175311189269863, 'max_depth': 4, 'min_child_weight': 7, 'subsample': 0.8958194373424189, 'colsample_bytree': 0.8612545432774058, 'gamma': 4.335481404131988, 'reg_alpha': 3.9889206285902584e-08, 'reg_lambda': 0.0024440024980574584}. Best is trial 34 with value: 274.699031829834.
[I 2026-10-02 18:22:49,695] Trial 40 finished with value: 287.85222244262695 and parameters: {'n_estimators': 353, 'learning_rate': 0.08576022684342349, 'max_depth': 4, 'min_child_weight': 6, 'subsample': 0.9386363383514706, 'colsample_bytree': 0.8361567595296638, 'gamma': 4.550813427129203, 'reg_alpha': 0.0001659773515213793, 'reg_lambda': 0.0019608374163865416}. Best is trial 34 with value: 274.699031829834.
[I 2026-10-02 18:22:50,293] Trial 41 finished with value: 273.5597839355469 and parameters: {'n_estimators': 437, 'learning_rate': 0.08344105386444635, 'max_depth': 3, 'min_child_weight': 6, 'subsample': 0.943927313643166, 'colsample_bytree': 0.7626074328679981, 'gamma': 4.422817304854604, 'reg_alpha': 7.217252487272142e-07, 'reg_lambda': 0.00717754365768692}. Best is trial 41 with value: 273.5597839355469.
[I 2026-10-02 18:22:50,684] Trial 42 finished with value: 285.92091369628906 and parameters: {'n_estimators': 285, 'learning_rate': 0.07641023441105775, 'max_depth': 4, 'min_child_weight': 6, 'subsample': 0.9560237241508761, 'colsample_bytree': 0.6870253366707284, 'gamma': 4.452822881046061, 'reg_alpha': 1.1110116339187723e-07, 'reg_lambda': 0.004205847648500366}. Best is trial 41 with value: 273.5597839355469.
[I 2026-10-02 18:22:51,475] Trial 43 finished with value: 275.25304412841797 and parameters: {'n_estimators': 625, 'learning_rate': 0.06352426479500511, 'max_depth': 3, 'min_child_weight': 6, 'subsample': 0.941045829842886, 'colsample_bytree': 0.8129201694191825, 'gamma': 4.670071045470001, 'reg_alpha': 2.3244368326335467e-06, 'reg_lambda': 0.013060123605709401}. Best is trial 41 with value: 273.5597839355469.
[I 2026-10-02 18:22:52,264] Trial 44 finished with value: 283.36450958251953 and parameters: {'n_estimators': 533, 'learning_rate': 0.1306398434064557, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.9752740783468133, 'colsample_bytree': 0.8947819749155969, 'gamma': 4.546176725341621, 'reg_alpha': 2.1196972661654824e-07, 'reg_lambda': 0.005700132508918517}. Best is trial 41 with value: 273.5597839355469.
[I 2026-10-02 18:22:52,915] Trial 45 finished with value: 277.2797737121582 and parameters: {'n_estimators': 467, 'learning_rate': 0.10175671573752035, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.8906253227751718, 'colsample_bytree': 0.7524434459345077, 'gamma': 4.400189893424613, 'reg_alpha': 3.805011769491891e-07, 'reg_lambda': 0.0237721719862383}. Best is trial 41 with value: 273.5597839355469.
[I 2026-10-02 18:22:53,448] Trial 46 finished with value: 277.49299240112305 and parameters: {'n_estimators': 421, 'learning_rate': 0.06985578701972123, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.9785101448454021, 'colsample_bytree': 0.782983940243595, 'gamma': 4.006777831294235, 'reg_alpha': 1.3233031826689268e-07, 'reg_lambda': 0.0019598294270841738}. Best is trial 41 with value: 273.5597839355469.
[I 2026-10-02 18:22:53,980] Trial 47 finished with value: 284.5717544555664 and parameters: {'n_estimators': 403, 'learning_rate': 0.12893476535177925, 'max_depth': 3, 'min_child_weight': 6, 'subsample': 0.9098933957051415, 'colsample_bytree': 0.8099083311281674, 'gamma': 4.156199646178661, 'reg_alpha': 3.313557503699135e-08, 'reg_lambda': 0.007196629992952541}. Best is trial 41 with value: 273.5597839355469.

In [11]:
print("Best CV RMSE:")
print(study.best_value)

print("\nBest parameters:")

for param, value in study.best_params.items():
    print(f"{param}: {value}")

Best CV RMSE:
268.64988708496094

Best parameters:
n_estimators: 735
learning_rate: 0.044974970480514756
max_depth: 3
min_child_weight: 6
subsample: 0.9726604916803252
colsample_bytree: 0.6624985904843348
gamma: 4.742422084291189
reg_alpha: 4.301446920624345e-07
reg_lambda: 0.01813392065633835

In [12]:
best_params = study.best_params

seeds = [0, 1, 2, 3, 42]

results = []

for seed in seeds:

    model = xgb.XGBRegressor(
        **best_params,
        objective="reg:squarederror",
        random_state=seed,
        n_jobs=-1
    )

    model.fit(
        X_train,
        y_train
    )

    y_pred = model.predict(X_val)

    results.append({
        "Seed": seed,
        "RMSE": root_mean_squared_error(y_val, y_pred),
        "MSE": mean_squared_error(y_val, y_pred),
        "MAE": mean_absolute_error(y_val, y_pred),
        "MAPE": mean_absolute_percentage_error(y_val, y_pred),
        "R2": r2_score(y_val, y_pred)
    })

stability_df = pd.DataFrame(results)

stability_summary = stability_df.drop(
    columns="Seed"
).agg(["mean", "std", "min", "max"]).T

print("=== Results by seed ===")
display(stability_df)

print("\n=== Stability summary ===")
display(stability_summary)

=== Results by seed ===

   Seed        RMSE           MSE         MAE      MAPE        R2
0     0  191.021301  36489.136719  140.947617  0.067398  0.779133
1     1  192.511795  37060.792969  141.847275  0.067816  0.775673
2     2  191.875931  36816.371094  141.244934  0.067498  0.777152
3     3  191.814819  36792.925781  141.405273  0.067595  0.777294
4    42  192.216568  36947.210938  141.718582  0.067745  0.776360

=== Stability summary ===

              mean         std           min           max
RMSE    191.888083    0.559854    191.021301    192.511795
MSE   36821.287500  214.692968  36489.136719  37060.792969
MAE     141.432736    0.362255    140.947617    141.847275
MAPE      0.067610    0.000172      0.067398      0.067816
R2        0.777122    0.001300      0.775673      0.779133

In [13]:
stability_df.to_csv("../report/seed_pls_val_report.csv", index = False)
stability_summary.to_csv("../report/seed_summary_pls_val_report.csv", index = False)

# 4. Final Training on year 1 and year 2

In [14]:
df_train, df_test = build_features(
                                df_train = pd.read_excel("../Dataset/training.xlsx"), 
                                df_test = pd.read_excel("../Dataset/testing.xlsx")
                                   )

In [15]:
X_train = df_train[features]
y_train = df_train[target]

X_test = df_test[features]

In [16]:
print("Dataset sizes:")
print(f"Train (Year 1): {len(X_train):,}")
print(f"Validation (Year 2): {len(X_val):,}")
print(f"Test (Year 3): {len(X_test):,}")

Dataset sizes:
Train (Year 1): 17,544
Validation (Year 2): 8,760
Test (Year 3): 8,760

In [19]:
seeds = [0, 1, 2, 3, 42]

test_predictions = []

for seed in seeds:

    model = xgb.XGBRegressor(
        **best_params,
        objective="reg:squarederror",
        random_state=seed,
        n_jobs=-1
    )

    model.fit(
        X_train,
        y_train
    )

    pred = model.predict(X_test)

    test_predictions.append(pred)

y_test_pred = np.mean(
    test_predictions,
    axis=0
)

In [20]:
pd.DataFrame(y_test_pred).to_csv("../report/pls_test_prediction.csv", index = False)