# 1. Import Libraries

In [1]:
import sys
from pathlib import Path

# Thêm thư mục gốc (project root) vào Python path
project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

import pandas as pd
import xgboost as xgb

from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, mean_absolute_percentage_error, root_mean_squared_error

import numpy as np

from utils.features import build_features

import optuna

# 2. Load Dataset

In [2]:
df_train, df_val = build_features(
                                df_train = pd.read_excel("../Dataset/training.xlsx"), 
                                df_test = None,
                                pls_fit_years = [1]
                                   )

In [3]:
features = [
    'Year', 'Month', 'Day', 'Hour',
    'Combined_Temp',
    'Combined_GHI_1', 'Combined_GHI_2',
    'sin_day_k1', 'cos_day_k1'
]
target = 'Load'

# 3. Split Data

In [4]:
# Year 1 → TRAIN
train_mask = df_train['Year'] == 1

# Year 2 → VALIDATION
val_mask = df_val['Year'] == 2

# Year 3 → TEST
# Testing.xlsx is assumed to contain Year 3

X_train = df_train.loc[train_mask, features]
y_train = df_train.loc[train_mask, target]

X_val = df_val.loc[val_mask, features]
y_val = df_val.loc[val_mask, target]

print("Dataset sizes:")
print(f"Train (Year 1): {len(X_train):,}")
print(f"Validation (Year 2): {len(X_val):,}")

Dataset sizes:
Train (Year 1): 8,784
Validation (Year 2): 8,760

# 4. Train on year 1, evaluate on year 2

In [5]:
tscv = TimeSeriesSplit(n_splits=4)

In [6]:
def objective(trial):

    params = {
        "objective": "reg:squarederror",

        "n_estimators": trial.suggest_int(
            "n_estimators",
            100,
            1500
        ),

        "learning_rate": trial.suggest_float(
            "learning_rate",
            0.01,
            0.2,
            log=True
        ),

        "max_depth": trial.suggest_int(
            "max_depth",
            3,
            10
        ),

        "min_child_weight": trial.suggest_int(
            "min_child_weight",
            1,
            10
        ),

        "subsample": trial.suggest_float(
            "subsample",
            0.6,
            1.0
        ),

        "colsample_bytree": trial.suggest_float(
            "colsample_bytree",
            0.6,
            1.0
        ),

        "gamma": trial.suggest_float(
            "gamma",
            0,
            5
        ),

        "reg_alpha": trial.suggest_float(
            "reg_alpha",
            1e-8,
            10,
            log=True
        ),

        "reg_lambda": trial.suggest_float(
            "reg_lambda",
            1e-3,
            10,
            log=True
        ),

        "random_state": 42,
        "n_jobs": -1
    }

    fold_rmse = []

    # ============================================
    # Time-series CV trên YEAR 1
    # ============================================

    for train_idx, val_idx in tscv.split(X_train):

        X_fold_train = X_train.iloc[train_idx]
        X_fold_val = X_train.iloc[val_idx]

        y_fold_train = y_train.iloc[train_idx]
        y_fold_val = y_train.iloc[val_idx]

        model = xgb.XGBRegressor(**params)

        model.fit(
            X_fold_train,
            y_fold_train
        )

        y_pred = model.predict(
            X_fold_val
        )

        rmse = root_mean_squared_error(
            y_fold_val,
            y_pred
        )

        fold_rmse.append(rmse)

    # Optuna minimize mean CV RMSE
    return np.mean(fold_rmse)

In [7]:
study = optuna.create_study(
    direction="minimize",
    study_name="xgb_year1_timeseries_cv"
)

study.optimize(
    objective,
    n_trials=100,
    show_progress_bar=True
)

[I 2026-10-02 18:33:04,301] A new study created in memory with name: xgb_year1_timeseries_cv

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-10-02 18:33:05,542] Trial 0 finished with value: 284.00377655029297 and parameters: {'n_estimators': 685, 'learning_rate': 0.044736908001172616, 'max_depth': 4, 'min_child_weight': 6, 'subsample': 0.7888584027887461, 'colsample_bytree': 0.930961321832862, 'gamma': 3.542986991070409, 'reg_alpha': 8.937226797318606e-07, 'reg_lambda': 0.1035546113101104}. Best is trial 0 with value: 284.00377655029297.
[I 2026-10-02 18:33:11,916] Trial 1 finished with value: 310.5249710083008 and parameters: {'n_estimators': 1266, 'learning_rate': 0.016043210664298455, 'max_depth': 9, 'min_child_weight': 1, 'subsample': 0.779804911302939, 'colsample_bytree': 0.8270278165523471, 'gamma': 4.155792418863769, 'reg_alpha': 1.007153749335402e-08, 'reg_lambda': 0.007305652877433276}. Best is trial 0 with value: 284.00377655029297.
[I 2026-10-02 18:33:13,392] Trial 2 finished with value: 308.4929428100586 and parameters: {'n_estimators': 832, 'learning_rate': 0.03172378269423598, 'max_depth': 6, 'min_child_weight': 8, 'subsample': 0.8177268062484061, 'colsample_bytree': 0.6125648944819625, 'gamma': 4.147136810213824, 'reg_alpha': 0.2896687366684406, 'reg_lambda': 9.695407472853308}. Best is trial 0 with value: 284.00377655029297.
[I 2026-10-02 18:33:14,873] Trial 3 finished with value: 316.99584197998047 and parameters: {'n_estimators': 957, 'learning_rate': 0.09472470524505316, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.8395715050233487, 'colsample_bytree': 0.8685376013793173, 'gamma': 2.87181391937493, 'reg_alpha': 0.0950117103133856, 'reg_lambda': 0.023648369538917205}. Best is trial 0 with value: 284.00377655029297.
[I 2026-10-02 18:33:16,923] Trial 4 finished with value: 304.45167541503906 and parameters: {'n_estimators': 1060, 'learning_rate': 0.015427961229539228, 'max_depth': 6, 'min_child_weight': 10, 'subsample': 0.8174999640901922, 'colsample_bytree': 0.6013763316524531, 'gamma': 4.0588082517299, 'reg_alpha': 6.410443575456238e-08, 'reg_lambda': 0.7776587846507128}. Best is trial 0 with value: 284.00377655029297.
[I 2026-10-02 18:33:17,563] Trial 5 finished with value: 303.2085876464844 and parameters: {'n_estimators': 292, 'learning_rate': 0.014081381472356332, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.8366544299642353, 'colsample_bytree': 0.7416346314536149, 'gamma': 4.94909016871394, 'reg_alpha': 0.15081004881635915, 'reg_lambda': 0.38562614763192204}. Best is trial 0 with value: 284.00377655029297.
[I 2026-10-02 18:33:17,970] Trial 6 finished with value: 290.3645133972168 and parameters: {'n_estimators': 365, 'learning_rate': 0.17925475441765965, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.8882445112911774, 'colsample_bytree': 0.9021191321326819, 'gamma': 0.6376693011834073, 'reg_alpha': 1.9073655333525427e-05, 'reg_lambda': 0.04653690961520529}. Best is trial 0 with value: 284.00377655029297.
[I 2026-10-02 18:33:19,007] Trial 7 finished with value: 298.54040145874023 and parameters: {'n_estimators': 314, 'learning_rate': 0.14993107326485985, 'max_depth': 9, 'min_child_weight': 5, 'subsample': 0.7692754697072924, 'colsample_bytree': 0.6243637453509447, 'gamma': 2.874747194350605, 'reg_alpha': 4.405266370882493, 'reg_lambda': 0.004442660181323255}. Best is trial 0 with value: 284.00377655029297.
[I 2026-10-02 18:33:20,951] Trial 8 finished with value: 322.9328079223633 and parameters: {'n_estimators': 854, 'learning_rate': 0.15969743138788037, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.8059543909031772, 'colsample_bytree': 0.7797635992355592, 'gamma': 3.527121436113179, 'reg_alpha': 1.7619229222783498e-06, 'reg_lambda': 0.23008634161541164}. Best is trial 0 with value: 284.00377655029297.
[I 2026-10-02 18:33:22,822] Trial 9 finished with value: 304.58099365234375 and parameters: {'n_estimators': 958, 'learning_rate': 0.038259875357015784, 'max_depth': 6, 'min_child_weight': 5, 'subsample': 0.7476431980418476, 'colsample_bytree': 0.8221415039085456, 'gamma': 3.2247555785191047, 'reg_alpha': 1.919682812496594e-05, 'reg_lambda': 0.03838967250374609}. Best is trial 0 with value: 284.00377655029297.
[I 2026-10-02 18:33:24,363] Trial 10 finished with value: 295.0386390686035 and parameters: {'n_estimators': 538, 'learning_rate': 0.022825334496499733, 'max_depth': 8, 'min_child_weight': 8, 'subsample': 0.6796169665027204, 'colsample_bytree': 0.974080316602953, 'gamma': 1.4425360122885138, 'reg_alpha': 1.5085468276726514e-08, 'reg_lambda': 0.02598166530078617}. Best is trial 0 with value: 284.00377655029297.
[I 2026-10-02 18:33:25,276] Trial 11 finished with value: 283.8832550048828 and parameters: {'n_estimators': 639, 'learning_rate': 0.046292263377243986, 'max_depth': 4, 'min_child_weight': 6, 'subsample': 0.7459204659918173, 'colsample_bytree': 0.9218167402108208, 'gamma': 0.9879805837028122, 'reg_alpha': 5.4638041346771324e-08, 'reg_lambda': 0.024943885985001663}. Best is trial 11 with value: 283.8832550048828.
[I 2026-10-02 18:33:26,252] Trial 12 finished with value: 284.4275932312012 and parameters: {'n_estimators': 727, 'learning_rate': 0.047315701506333324, 'max_depth': 4, 'min_child_weight': 6, 'subsample': 0.6994572197377301, 'colsample_bytree': 0.8891417716888583, 'gamma': 0.5165417378763166, 'reg_alpha': 2.956193966898548e-07, 'reg_lambda': 0.04398133545334622}. Best is trial 11 with value: 283.8832550048828.
[I 2026-10-02 18:33:27,302] Trial 13 finished with value: 288.02743911743164 and parameters: {'n_estimators': 707, 'learning_rate': 0.040022138556165605, 'max_depth': 4, 'min_child_weight': 6, 'subsample': 0.7402513434683307, 'colsample_bytree': 0.9139542066200209, 'gamma': 4.751097076102535, 'reg_alpha': 1.1809411478709131e-08, 'reg_lambda': 0.004438578999891241}. Best is trial 11 with value: 283.8832550048828.
[I 2026-10-02 18:33:28,069] Trial 14 finished with value: 278.0767250061035 and parameters: {'n_estimators': 677, 'learning_rate': 0.022600876733434885, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.7227742187343913, 'colsample_bytree': 0.9804702069020554, 'gamma': 2.81389416815053, 'reg_alpha': 1.4404208537435693e-08, 'reg_lambda': 0.0405790739805203}. Best is trial 14 with value: 278.0767250061035.
[I 2026-10-02 18:33:28,822] Trial 15 finished with value: 285.2530174255371 and parameters: {'n_estimators': 664, 'learning_rate': 0.08577017350297021, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.7729671652666628, 'colsample_bytree': 0.9823214935756474, 'gamma': 2.240182516026278, 'reg_alpha': 1.2564778441847485e-08, 'reg_lambda': 0.008087922229975501}. Best is trial 14 with value: 278.0767250061035.
[I 2026-10-02 18:33:29,487] Trial 16 finished with value: 278.37795639038086 and parameters: {'n_estimators': 580, 'learning_rate': 0.026268869664589578, 'max_depth': 3, 'min_child_weight': 5, 'subsample': 0.7806159267066677, 'colsample_bytree': 0.9111778449143777, 'gamma': 1.9097236079900888, 'reg_alpha': 3.0925977889305e-06, 'reg_lambda': 0.008840584619845198}. Best is trial 14 with value: 278.0767250061035.
[I 2026-10-02 18:33:30,570] Trial 17 finished with value: 278.53719329833984 and parameters: {'n_estimators': 910, 'learning_rate': 0.036485106593337, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.6882473605419183, 'colsample_bytree': 0.9333156658636848, 'gamma': 2.229289099714327, 'reg_alpha': 7.142271933081079e-06, 'reg_lambda': 0.004065483583178336}. Best is trial 14 with value: 278.0767250061035.
[I 2026-10-02 18:33:31,380] Trial 18 finished with value: 280.0028877258301 and parameters: {'n_estimators': 724, 'learning_rate': 0.021289856212969988, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.7819425722155477, 'colsample_bytree': 0.887076725024542, 'gamma': 4.069767015563623, 'reg_alpha': 1.1542425902898019e-08, 'reg_lambda': 0.38839924044030755}. Best is trial 14 with value: 278.0767250061035.
[I 2026-10-02 18:33:32,833] Trial 19 finished with value: 292.3794937133789 and parameters: {'n_estimators': 656, 'learning_rate': 0.02040352249299974, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6808443241760335, 'colsample_bytree': 0.9810216363508264, 'gamma': 2.7051616125851052, 'reg_alpha': 4.902407997825673e-06, 'reg_lambda': 0.03263247027178321}. Best is trial 14 with value: 278.0767250061035.
[I 2026-10-02 18:33:33,696] Trial 20 finished with value: 278.56220626831055 and parameters: {'n_estimators': 773, 'learning_rate': 0.020252733932382878, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.696578702983413, 'colsample_bytree': 0.9193967617576295, 'gamma': 3.5460862237246293, 'reg_alpha': 1.338939576043091e-07, 'reg_lambda': 0.004913959209010873}. Best is trial 14 with value: 278.0767250061035.
[I 2026-10-02 18:33:34,326] Trial 21 finished with value: 284.15393447875977 and parameters: {'n_estimators': 490, 'learning_rate': 0.019489730193382206, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.7006868236789091, 'colsample_bytree': 0.9884157530978612, 'gamma': 1.6741622722581042, 'reg_alpha': 3.834352894380963e-05, 'reg_lambda': 0.05081053093103978}. Best is trial 14 with value: 278.0767250061035.
[I 2026-10-02 18:33:34,925] Trial 22 finished with value: 278.6851272583008 and parameters: {'n_estimators': 516, 'learning_rate': 0.03399625623632788, 'max_depth': 3, 'min_child_weight': 5, 'subsample': 0.8340149404091447, 'colsample_bytree': 0.9725785378349545, 'gamma': 2.1203438825939642, 'reg_alpha': 2.2478933027502198e-07, 'reg_lambda': 0.00439219459987525}. Best is trial 14 with value: 278.0767250061035.
[I 2026-10-02 18:33:35,610] Trial 23 finished with value: 284.32276916503906 and parameters: {'n_estimators': 499, 'learning_rate': 0.014918930016167077, 'max_depth': 4, 'min_child_weight': 6, 'subsample': 0.7459494594651437, 'colsample_bytree': 0.9123385024774161, 'gamma': 1.6329218013018554, 'reg_alpha': 9.827936408558787e-08, 'reg_lambda': 0.0069417657507444405}. Best is trial 14 with value: 278.0767250061035.
[I 2026-10-02 18:33:36,936] Trial 24 finished with value: 296.79008865356445 and parameters: {'n_estimators': 950, 'learning_rate': 0.07184592090877662, 'max_depth': 4, 'min_child_weight': 7, 'subsample': 0.6916881466859545, 'colsample_bytree': 0.9405826514351502, 'gamma': 1.6466743001390025, 'reg_alpha': 5.161259448547622e-05, 'reg_lambda': 0.0016656182699674653}. Best is trial 14 with value: 278.0767250061035.
[I 2026-10-02 18:33:37,795] Trial 25 finished with value: 283.59489822387695 and parameters: {'n_estimators': 719, 'learning_rate': 0.014866705897650068, 'max_depth': 3, 'min_child_weight': 5, 'subsample': 0.759733182701944, 'colsample_bytree': 0.9919107087035332, 'gamma': 3.385902109347378, 'reg_alpha': 1.54352645870142e-06, 'reg_lambda': 0.06397065740244194}. Best is trial 14 with value: 278.0767250061035.
[I 2026-10-02 18:33:38,946] Trial 26 finished with value: 284.2216377258301 and parameters: {'n_estimators': 674, 'learning_rate': 0.03334157946806078, 'max_depth': 4, 'min_child_weight': 5, 'subsample': 0.7335134342565931, 'colsample_bytree': 0.9238979003609905, 'gamma': 2.348725448759028, 'reg_alpha': 0.0015325282839500588, 'reg_lambda': 0.0011318818381361167}. Best is trial 14 with value: 278.0767250061035.
[I 2026-10-02 18:33:39,704] Trial 27 finished with value: 284.1722831726074 and parameters: {'n_estimators': 509, 'learning_rate': 0.014538098991191484, 'max_depth': 4, 'min_child_weight': 4, 'subsample': 0.7747719775748609, 'colsample_bytree': 0.9888555014228595, 'gamma': 2.1446761303410966, 'reg_alpha': 1.1183596286522637e-08, 'reg_lambda': 0.006800699324369875}. Best is trial 14 with value: 278.0767250061035.
[I 2026-10-02 18:33:40,537] Trial 28 finished with value: 278.1888961791992 and parameters: {'n_estimators': 799, 'learning_rate': 0.04330784837469878, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.6711539007715261, 'colsample_bytree': 0.9739629025345002, 'gamma': 2.4401989549257608, 'reg_alpha': 3.7300147027778426e-08, 'reg_lambda': 0.0011206165272458343}. Best is trial 14 with value: 278.0767250061035.
[I 2026-10-02 18:33:41,544] Trial 29 finished with value: 282.7054100036621 and parameters: {'n_estimators': 795, 'learning_rate': 0.02855066988174336, 'max_depth': 4, 'min_child_weight': 4, 'subsample': 0.6266377935154179, 'colsample_bytree': 0.9957672945398586, 'gamma': 2.773488830343066, 'reg_alpha': 3.08026411119047e-07, 'reg_lambda': 0.0011846626447025107}. Best is trial 14 with value: 278.0767250061035.
[I 2026-10-02 18:33:43,138] Trial 30 finished with value: 291.997127532959 and parameters: {'n_estimators': 854, 'learning_rate': 0.032008468972585746, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.7271057876750946, 'colsample_bytree': 0.9806951260342848, 'gamma': 2.816335528450888, 'reg_alpha': 4.5064721694410683e-07, 'reg_lambda': 0.007347570814122391}. Best is trial 14 with value: 278.0767250061035.
[I 2026-10-02 18:33:43,789] Trial 31 finished with value: 278.39266204833984 and parameters: {'n_estimators': 634, 'learning_rate': 0.02425911184249603, 'max_depth': 3, 'min_child_weight': 5, 'subsample': 0.7101700806636175, 'colsample_bytree': 0.8835518416291395, 'gamma': 2.4617722009803695, 'reg_alpha': 2.7799701224051624e-06, 'reg_lambda': 0.07531648289627191}. Best is trial 14 with value: 278.0767250061035.
[I 2026-10-02 18:33:44,643] Trial 32 finished with value: 277.2879829406738 and parameters: {'n_estimators': 756, 'learning_rate': 0.025835528126719305, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.7814563160597713, 'colsample_bytree': 0.9565435321832902, 'gamma': 1.7371113141550785, 'reg_alpha': 4.448628918503292e-06, 'reg_lambda': 0.10979124388009745}. Best is trial 32 with value: 277.2879829406738.
[I 2026-10-02 18:33:45,542] Trial 33 finished with value: 278.166202545166 and parameters: {'n_estimators': 743, 'learning_rate': 0.060308135553687886, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.6467332731909446, 'colsample_bytree': 0.9455357382610193, 'gamma': 2.051019535614046, 'reg_alpha': 9.522756221073102e-07, 'reg_lambda': 0.002977989563539452}. Best is trial 32 with value: 277.2879829406738.
[I 2026-10-02 18:33:46,219] Trial 34 finished with value: 277.0855178833008 and parameters: {'n_estimators': 639, 'learning_rate': 0.032073112878548145, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.6756792637990605, 'colsample_bytree': 0.9135990051143419, 'gamma': 2.3636692279553997, 'reg_alpha': 1.8541229816971911e-06, 'reg_lambda': 0.0022172351421905685}. Best is trial 34 with value: 277.0855178833008.
[I 2026-10-02 18:33:47,007] Trial 35 finished with value: 275.8486022949219 and parameters: {'n_estimators': 640, 'learning_rate': 0.026007052722979592, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.6607419978103036, 'colsample_bytree': 0.9414193676707424, 'gamma': 1.9091309957305749, 'reg_alpha': 4.1723323548503034e-06, 'reg_lambda': 0.0013171663354100177}. Best is trial 35 with value: 275.8486022949219.
[I 2026-10-02 18:33:47,505] Trial 36 finished with value: 279.41784286499023 and parameters: {'n_estimators': 458, 'learning_rate': 0.03292717261200236, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.6345744424116772, 'colsample_bytree': 0.912425194764391, 'gamma': 2.0689777780627634, 'reg_alpha': 1.2587026961213362e-05, 'reg_lambda': 0.0018882877353004405}. Best is trial 35 with value: 275.8486022949219.
[I 2026-10-02 18:33:48,562] Trial 37 finished with value: 277.85795974731445 and parameters: {'n_estimators': 778, 'learning_rate': 0.024316165301835814, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.7729183289674597, 'colsample_bytree': 0.8912652993782, 'gamma': 1.6443345141506305, 'reg_alpha': 6.673659687276872e-08, 'reg_lambda': 0.07441520776143556}. Best is trial 35 with value: 275.8486022949219.
[I 2026-10-02 18:33:49,249] Trial 38 finished with value: 287.1358184814453 and parameters: {'n_estimators': 442, 'learning_rate': 0.033536886982367446, 'max_depth': 4, 'min_child_weight': 5, 'subsample': 0.731434821641665, 'colsample_bytree': 0.9772072921066541, 'gamma': 2.1014872687365593, 'reg_alpha': 1.6294033821647404e-05, 'reg_lambda': 0.0014256642564714087}. Best is trial 35 with value: 275.8486022949219.
[I 2026-10-02 18:33:49,961] Trial 39 finished with value: 280.9145050048828 and parameters: {'n_estimators': 503, 'learning_rate': 0.023126200613068144, 'max_depth': 4, 'min_child_weight': 4, 'subsample': 0.7241204798830622, 'colsample_bytree': 0.9268174227055516, 'gamma': 1.900083610610538, 'reg_alpha': 8.000607040619387e-06, 'reg_lambda': 0.0029490086443647126}. Best is trial 35 with value: 275.8486022949219.
[I 2026-10-02 18:33:50,626] Trial 40 finished with value: 281.47180938720703 and parameters: {'n_estimators': 420, 'learning_rate': 0.02567580667727058, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.7010020935705296, 'colsample_bytree': 0.9507618283553058, 'gamma': 1.486316916103113, 'reg_alpha': 5.74109667170208e-06, 'reg_lambda': 0.0019103124859981514}. Best is trial 35 with value: 275.8486022949219.
[I 2026-10-02 18:33:51,357] Trial 41 finished with value: 288.4463539123535 and parameters: {'n_estimators': 582, 'learning_rate': 0.015067174195471836, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.7983099050091569, 'colsample_bytree': 0.9535990443935347, 'gamma': 2.9403230911226372, 'reg_alpha': 2.1830386784511925e-08, 'reg_lambda': 0.02972088930440555}. Best is trial 35 with value: 275.8486022949219.
[I 2026-10-02 18:33:52,248] Trial 42 finished with value: 282.65856170654297 and parameters: {'n_estimators': 651, 'learning_rate': 0.01712072554471236, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.6615936133132375, 'colsample_bytree': 0.9740335993954655, 'gamma': 2.492370442651847, 'reg_alpha': 1.4161348226345462e-06, 'reg_lambda': 0.004447335781430922}. Best is trial 35 with value: 275.8486022949219.
[I 2026-10-02 18:33:52,834] Trial 43 finished with value: 283.09984588623047 and parameters: {'n_estimators': 444, 'learning_rate': 0.023662621491858958, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.6531503123413972, 'colsample_bytree': 0.8736210600086443, 'gamma': 1.9482117035242879, 'reg_alpha': 3.4771998853393153e-06, 'reg_lambda': 0.002561051183861249}. Best is trial 35 with value: 275.8486022949219.
[I 2026-10-02 18:33:53,752] Trial 44 finished with value: 278.23704528808594 and parameters: {'n_estimators': 720, 'learning_rate': 0.02118398037788069, 'max_depth': 3, 'min_child_weight': 5, 'subsample': 0.7165564094301942, 'colsample_bytree': 0.9704445872592931, 'gamma': 2.006461975516564, 'reg_alpha': 1.1252864828846848e-08, 'reg_lambda': 0.09543809713656774}. Best is trial 35 with value: 275.8486022949219.
[I 2026-10-02 18:33:54,384] Trial 45 finished with value: 277.6116180419922 and parameters: {'n_estimators': 433, 'learning_rate': 0.02847927718965768, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.6374207423821371, 'colsample_bytree': 0.9352645019201906, 'gamma': 2.1251138995071455, 'reg_alpha': 5.313089204351167e-07, 'reg_lambda': 0.009931624172576368}. Best is trial 35 with value: 275.8486022949219.
[I 2026-10-02 18:33:55,116] Trial 46 finished with value: 275.7594566345215 and parameters: {'n_estimators': 522, 'learning_rate': 0.03520501653377715, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.685920506761982, 'colsample_bytree': 0.9032549255513519, 'gamma': 2.101968566635402, 'reg_alpha': 3.526836149897829e-06, 'reg_lambda': 0.008737913210336292}. Best is trial 46 with value: 275.7594566345215.
[I 2026-10-02 18:33:55,883] Trial 47 finished with value: 280.9721908569336 and parameters: {'n_estimators': 602, 'learning_rate': 0.01864664601540781, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.6762326828417092, 'colsample_bytree': 0.8982133987524001, 'gamma': 1.8011222570025636, 'reg_alpha': 1.7137239542483023e-06, 'reg_lambda': 0.0024743263654569718}. Best is trial 46 with value: 275.7594566345215.

In [8]:
print("Best CV RMSE:")
print(study.best_value)

print("\nBest parameters:")

for param, value in study.best_params.items():
    print(f"{param}: {value}")

Best CV RMSE:
274.45149993896484

Best parameters:
n_estimators: 736
learning_rate: 0.024661591078667625
max_depth: 3
min_child_weight: 5
subsample: 0.6446702352361038
colsample_bytree: 0.913082298530404
gamma: 3.30729385200618
reg_alpha: 7.120808185588972e-06
reg_lambda: 0.0013814972364974353

In [9]:
best_params = study.best_params

seeds = [0, 1, 2, 3, 42]

results = []

for seed in seeds:

    model = xgb.XGBRegressor(
        **best_params,
        objective="reg:squarederror",
        random_state=seed,
        n_jobs=-1
    )

    model.fit(
        X_train,
        y_train
    )

    y_pred = model.predict(X_val)

    results.append({
        "Seed": seed,
        "RMSE": root_mean_squared_error(y_val, y_pred),
        "MSE": mean_squared_error(y_val, y_pred),
        "MAE": mean_absolute_error(y_val, y_pred),
        "MAPE": mean_absolute_percentage_error(y_val, y_pred),
        "R2": r2_score(y_val, y_pred)
    })

stability_df = pd.DataFrame(results)

stability_summary = stability_df.drop(
    columns="Seed"
).agg(["mean", "std", "min", "max"]).T

print("=== Results by seed ===")
display(stability_df)

print("\n=== Stability summary ===")
display(stability_summary)

=== Results by seed ===

   Seed        RMSE           MSE         MAE      MAPE        R2
0     0  192.156494  36924.117188  141.414642  0.067464  0.776500
1     1  191.290802  36592.171875  140.713531  0.067055  0.778509
2     2  191.591248  36707.207031  140.878052  0.067172  0.777813
3     3  191.130035  36530.691406  140.598541  0.067050  0.778881
4    42  191.407745  36636.925781  140.793381  0.067152  0.778238

=== Stability summary ===

              mean         std           min           max
RMSE    191.515265    0.396010    191.130035    192.156494
MSE   36678.222656  151.805676  36530.691406  36924.117188
MAE     140.879630    0.316338    140.598541    141.414642
MAPE      0.067179    0.000169      0.067050      0.067464
R2        0.777988    0.000919      0.776500      0.778881

In [10]:
stability_df.to_csv("../report/seed_daily_first_harmonic_val_report.csv", index = False)
stability_summary.to_csv("../report/seed_summary_daily_first_harmonic_val_report.csv", index = False)

# 4. Final Training on year 1 and year 2

In [11]:
df_train, df_test = build_features(
                                df_train = pd.read_excel("../Dataset/training.xlsx"), 
                                df_test = pd.read_excel("../Dataset/testing.xlsx")
                                   )

In [12]:
X_train = df_train[features]
y_train = df_train[target]

X_test = df_test[features]

In [13]:
print("Dataset sizes:")
print(f"Train (Year 1): {len(X_train):,}")
print(f"Validation (Year 2): {len(X_val):,}")
print(f"Test (Year 3): {len(X_test):,}")

Dataset sizes:
Train (Year 1): 17,544
Validation (Year 2): 8,760
Test (Year 3): 8,760

In [16]:
seeds = [0, 1, 2, 3, 42]

test_predictions = []

for seed in seeds:

    model = xgb.XGBRegressor(
        **best_params,
        objective="reg:squarederror",
        random_state=seed,
        n_jobs=-1
    )

    model.fit(
        X_train,
        y_train
    )

    pred = model.predict(X_test)

    test_predictions.append(pred)

y_test_pred = np.mean(
    test_predictions,
    axis=0
)

In [17]:
pd.DataFrame(y_test_pred).to_csv("../report/daily_first_harmonic_test_prediction.csv", index = False)