# 1. Import Libraries

In [1]:
import sys
from pathlib import Path

# Thêm thư mục gốc (project root) vào Python path
project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

import pandas as pd
import xgboost as xgb

from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, mean_absolute_percentage_error, root_mean_squared_error

import numpy as np

from utils.features import build_features

import optuna

# 2. Load Dataset

In [2]:
df_train, df_val = build_features(
                                df_train = pd.read_excel("../Dataset/training.xlsx"), 
                                df_test = None,
                                pls_fit_years = [1]
                                   )

In [3]:
features = [
    'Year', 'Month', 'Day', 'Hour',
    'Combined_Temp',
    'Combined_GHI_1', 'Combined_GHI_2',
    'sin_day_k1', 'cos_day_k1',
    'sin_week_k1', 'cos_week_k1',
]
target = 'Load'

# 3. Split Data

In [4]:
# Year 1 → TRAIN
train_mask = df_train['Year'] == 1

# Year 2 → VALIDATION
val_mask = df_val['Year'] == 2

# Year 3 → TEST
# Testing.xlsx is assumed to contain Year 3

X_train = df_train.loc[train_mask, features]
y_train = df_train.loc[train_mask, target]

X_val = df_val.loc[val_mask, features]
y_val = df_val.loc[val_mask, target]

print("Dataset sizes:")
print(f"Train (Year 1): {len(X_train):,}")
print(f"Validation (Year 2): {len(X_val):,}")

Dataset sizes:
Train (Year 1): 8,784
Validation (Year 2): 8,760

# 4. Train on year 1, evaluate on year 2

In [5]:
tscv = TimeSeriesSplit(n_splits=4)

In [6]:
def objective(trial):

    params = {
        "objective": "reg:squarederror",

        "n_estimators": trial.suggest_int(
            "n_estimators",
            100,
            1500
        ),

        "learning_rate": trial.suggest_float(
            "learning_rate",
            0.01,
            0.2,
            log=True
        ),

        "max_depth": trial.suggest_int(
            "max_depth",
            3,
            10
        ),

        "min_child_weight": trial.suggest_int(
            "min_child_weight",
            1,
            10
        ),

        "subsample": trial.suggest_float(
            "subsample",
            0.6,
            1.0
        ),

        "colsample_bytree": trial.suggest_float(
            "colsample_bytree",
            0.6,
            1.0
        ),

        "gamma": trial.suggest_float(
            "gamma",
            0,
            5
        ),

        "reg_alpha": trial.suggest_float(
            "reg_alpha",
            1e-8,
            10,
            log=True
        ),

        "reg_lambda": trial.suggest_float(
            "reg_lambda",
            1e-3,
            10,
            log=True
        ),

        "random_state": 42,
        "n_jobs": -1
    }

    fold_rmse = []

    # ============================================
    # Time-series CV trên YEAR 1
    # ============================================

    for train_idx, val_idx in tscv.split(X_train):

        X_fold_train = X_train.iloc[train_idx]
        X_fold_val = X_train.iloc[val_idx]

        y_fold_train = y_train.iloc[train_idx]
        y_fold_val = y_train.iloc[val_idx]

        model = xgb.XGBRegressor(**params)

        model.fit(
            X_fold_train,
            y_fold_train
        )

        y_pred = model.predict(
            X_fold_val
        )

        rmse = root_mean_squared_error(
            y_fold_val,
            y_pred
        )

        fold_rmse.append(rmse)

    # Optuna minimize mean CV RMSE
    return np.mean(fold_rmse)

In [7]:
study = optuna.create_study(
    direction="minimize",
    study_name="xgb_year1_timeseries_cv"
)

study.optimize(
    objective,
    n_trials=100,
    show_progress_bar=True
)

[I 2026-10-02 18:36:52,711] A new study created in memory with name: xgb_year1_timeseries_cv

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-10-02 18:36:53,866] Trial 0 finished with value: 272.34679412841797 and parameters: {'n_estimators': 629, 'learning_rate': 0.029815109648957262, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.917874635934167, 'colsample_bytree': 0.7248094579283273, 'gamma': 2.0442054093473256, 'reg_alpha': 5.7211523062052425, 'reg_lambda': 0.11860723765336996}. Best is trial 0 with value: 272.34679412841797.
[I 2026-10-02 18:36:57,115] Trial 1 finished with value: 294.3945655822754 and parameters: {'n_estimators': 513, 'learning_rate': 0.01926439609105531, 'max_depth': 9, 'min_child_weight': 1, 'subsample': 0.8823406933870284, 'colsample_bytree': 0.7451077678539537, 'gamma': 3.8181121182157964, 'reg_alpha': 7.653299667890859, 'reg_lambda': 0.012200033686115976}. Best is trial 0 with value: 272.34679412841797.
[I 2026-10-02 18:37:02,268] Trial 2 finished with value: 295.27698516845703 and parameters: {'n_estimators': 1355, 'learning_rate': 0.04018058471825153, 'max_depth': 9, 'min_child_weight': 6, 'subsample': 0.7019101215401793, 'colsample_bytree': 0.6952049195266349, 'gamma': 4.797849366445838, 'reg_alpha': 2.419619282373358e-07, 'reg_lambda': 1.3182465985466847}. Best is trial 0 with value: 272.34679412841797.
[I 2026-10-02 18:37:06,068] Trial 3 finished with value: 300.345947265625 and parameters: {'n_estimators': 382, 'learning_rate': 0.012658359350407242, 'max_depth': 10, 'min_child_weight': 1, 'subsample': 0.6081394250709972, 'colsample_bytree': 0.6790119802702799, 'gamma': 0.9175498016987249, 'reg_alpha': 3.120886614872947, 'reg_lambda': 0.01078755053085483}. Best is trial 0 with value: 272.34679412841797.
[I 2026-10-02 18:37:07,413] Trial 4 finished with value: 280.7719535827637 and parameters: {'n_estimators': 971, 'learning_rate': 0.133396375225274, 'max_depth': 4, 'min_child_weight': 8, 'subsample': 0.8283091122601621, 'colsample_bytree': 0.8212928287544432, 'gamma': 0.8028938592966117, 'reg_alpha': 0.6573861507892294, 'reg_lambda': 0.924651389979583}. Best is trial 0 with value: 272.34679412841797.
[I 2026-10-02 18:37:08,199] Trial 5 finished with value: 296.96837615966797 and parameters: {'n_estimators': 161, 'learning_rate': 0.02753039163635517, 'max_depth': 9, 'min_child_weight': 8, 'subsample': 0.969690271204791, 'colsample_bytree': 0.7072287386446418, 'gamma': 2.9090329367599055, 'reg_alpha': 0.0008877907306821777, 'reg_lambda': 0.9793563446458163}. Best is trial 0 with value: 272.34679412841797.
[I 2026-10-02 18:37:10,619] Trial 6 finished with value: 284.2439994812012 and parameters: {'n_estimators': 599, 'learning_rate': 0.018388141781789737, 'max_depth': 10, 'min_child_weight': 9, 'subsample': 0.675946659417905, 'colsample_bytree': 0.7518269335124474, 'gamma': 0.23488609587257292, 'reg_alpha': 0.0017263075988695818, 'reg_lambda': 2.847435193672159}. Best is trial 0 with value: 272.34679412841797.
[I 2026-10-02 18:37:12,324] Trial 7 finished with value: 287.26953887939453 and parameters: {'n_estimators': 644, 'learning_rate': 0.057813128390672805, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6034405810369916, 'colsample_bytree': 0.8908099651122948, 'gamma': 4.247636955847838, 'reg_alpha': 2.60814050293635e-05, 'reg_lambda': 0.013513176374854496}. Best is trial 0 with value: 272.34679412841797.
[I 2026-10-02 18:37:19,465] Trial 8 finished with value: 287.14635467529297 and parameters: {'n_estimators': 1467, 'learning_rate': 0.014204033976530746, 'max_depth': 10, 'min_child_weight': 7, 'subsample': 0.895120170890924, 'colsample_bytree': 0.756383290747724, 'gamma': 4.363848049959657, 'reg_alpha': 1.4074170952083175e-08, 'reg_lambda': 0.004404657143518255}. Best is trial 0 with value: 272.34679412841797.
[I 2026-10-02 18:37:20,685] Trial 9 finished with value: 287.1556854248047 and parameters: {'n_estimators': 647, 'learning_rate': 0.021305505479304203, 'max_depth': 5, 'min_child_weight': 6, 'subsample': 0.8491134686674767, 'colsample_bytree': 0.7147862237773129, 'gamma': 1.2611677484008244, 'reg_alpha': 0.0039034624712226706, 'reg_lambda': 4.369396343729556}. Best is trial 0 with value: 272.34679412841797.
[I 2026-10-02 18:37:21,241] Trial 10 finished with value: 275.47725677490234 and parameters: {'n_estimators': 447, 'learning_rate': 0.036879480096703596, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.9470078547776246, 'colsample_bytree': 0.6016564031153018, 'gamma': 2.1912915730383165, 'reg_alpha': 6.586835490101292e-07, 'reg_lambda': 0.04025600335359715}. Best is trial 0 with value: 272.34679412841797.
[I 2026-10-02 18:37:22,259] Trial 11 finished with value: 268.4518356323242 and parameters: {'n_estimators': 675, 'learning_rate': 0.026590527251977313, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.8589049435835038, 'colsample_bytree': 0.6420358610514875, 'gamma': 1.761390423464829, 'reg_alpha': 0.7112698692133296, 'reg_lambda': 0.29680077654758563}. Best is trial 11 with value: 268.4518356323242.
[I 2026-10-02 18:37:23,750] Trial 12 finished with value: 270.27017974853516 and parameters: {'n_estimators': 1052, 'learning_rate': 0.01968887501752136, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.8457313706662842, 'colsample_bytree': 0.6280647854903803, 'gamma': 2.7370343026126935, 'reg_alpha': 0.3398841776994357, 'reg_lambda': 0.05985666479368351}. Best is trial 11 with value: 268.4518356323242.
[I 2026-10-02 18:37:25,294] Trial 13 finished with value: 265.0348358154297 and parameters: {'n_estimators': 1164, 'learning_rate': 0.0264270316205285, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.791926758935457, 'colsample_bytree': 0.6023450359147382, 'gamma': 2.2526965536433807, 'reg_alpha': 0.10007230745729592, 'reg_lambda': 0.7196758500683262}. Best is trial 13 with value: 265.0348358154297.
[I 2026-10-02 18:37:26,819] Trial 14 finished with value: 264.2106246948242 and parameters: {'n_estimators': 1154, 'learning_rate': 0.03343280719114502, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.7815496471075107, 'colsample_bytree': 0.649088882569483, 'gamma': 0.6372539737540781, 'reg_alpha': 0.2567032096218526, 'reg_lambda': 1.6746224386759325}. Best is trial 14 with value: 264.2106246948242.
[I 2026-10-02 18:37:28,778] Trial 15 finished with value: 284.1308288574219 and parameters: {'n_estimators': 1022, 'learning_rate': 0.01501970130570247, 'max_depth': 5, 'min_child_weight': 5, 'subsample': 0.7644317134064642, 'colsample_bytree': 0.6415999141047417, 'gamma': 0.3413207005310308, 'reg_alpha': 0.11400826240120872, 'reg_lambda': 1.2032824932260737}. Best is trial 14 with value: 264.2106246948242.
[I 2026-10-02 18:37:30,941] Trial 16 finished with value: 289.11795806884766 and parameters: {'n_estimators': 1083, 'learning_rate': 0.021213334843070183, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7097169932054197, 'colsample_bytree': 0.7087308084365869, 'gamma': 0.3949338324252212, 'reg_alpha': 8.010283194775113, 'reg_lambda': 7.0952892496779665}. Best is trial 14 with value: 264.2106246948242.
[I 2026-10-02 18:37:32,425] Trial 17 finished with value: 262.4262580871582 and parameters: {'n_estimators': 1229, 'learning_rate': 0.0435047260083732, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.7626872343529755, 'colsample_bytree': 0.6420274563516623, 'gamma': 1.9471499343596128, 'reg_alpha': 2.0112553712489674, 'reg_lambda': 0.7636341028541399}. Best is trial 17 with value: 262.4262580871582.
[I 2026-10-02 18:37:34,277] Trial 18 finished with value: 264.65491104125977 and parameters: {'n_estimators': 1429, 'learning_rate': 0.0505626013851592, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.8035708472092397, 'colsample_bytree': 0.7424954087423707, 'gamma': 0.011275684993576895, 'reg_alpha': 0.655528480779199, 'reg_lambda': 7.9134987067756555}. Best is trial 17 with value: 262.4262580871582.
[I 2026-10-02 18:37:36,529] Trial 19 finished with value: 288.42507553100586 and parameters: {'n_estimators': 1306, 'learning_rate': 0.06765881713983615, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7413349215780823, 'colsample_bytree': 0.6544687220284161, 'gamma': 0.7373650150415243, 'reg_alpha': 8.753700335048848, 'reg_lambda': 2.312854567369771}. Best is trial 17 with value: 262.4262580871582.
[I 2026-10-02 18:37:38,000] Trial 20 finished with value: 265.4334487915039 and parameters: {'n_estimators': 1189, 'learning_rate': 0.022587336392367933, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.7120494461336186, 'colsample_bytree': 0.7444867983190958, 'gamma': 1.6929241573101272, 'reg_alpha': 0.7287646183658156, 'reg_lambda': 1.1930375514047489}. Best is trial 17 with value: 262.4262580871582.
[I 2026-10-02 18:37:39,817] Trial 21 finished with value: 264.8528022766113 and parameters: {'n_estimators': 1365, 'learning_rate': 0.04714242385709089, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.7977304305044839, 'colsample_bytree': 0.7104668381575673, 'gamma': 1.0800933360725913, 'reg_alpha': 3.5067689749271964, 'reg_lambda': 0.19246509285969418}. Best is trial 17 with value: 262.4262580871582.
[I 2026-10-02 18:37:41,490] Trial 22 finished with value: 267.53173065185547 and parameters: {'n_estimators': 1421, 'learning_rate': 0.049394018048018684, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.731485450665686, 'colsample_bytree': 0.6845388651037724, 'gamma': 1.6222454931311725, 'reg_alpha': 0.038683529151630175, 'reg_lambda': 1.7498606281749767}. Best is trial 17 with value: 262.4262580871582.
[I 2026-10-02 18:37:43,095] Trial 23 finished with value: 266.1531524658203 and parameters: {'n_estimators': 1331, 'learning_rate': 0.07548678255428026, 'max_depth': 3, 'min_child_weight': 5, 'subsample': 0.8179736674934812, 'colsample_bytree': 0.7660062742669149, 'gamma': 0.6700844277805212, 'reg_alpha': 0.04810959060676602, 'reg_lambda': 5.115445707442812}. Best is trial 17 with value: 262.4262580871582.
[I 2026-10-02 18:37:44,593] Trial 24 finished with value: 262.13453674316406 and parameters: {'n_estimators': 1208, 'learning_rate': 0.030491142072164835, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.7621505323521063, 'colsample_bytree': 0.6389969622696106, 'gamma': 0.9947013983933877, 'reg_alpha': 8.478484857597008, 'reg_lambda': 0.665825327398986}. Best is trial 24 with value: 262.13453674316406.
[I 2026-10-02 18:37:45,708] Trial 25 finished with value: 266.39929580688477 and parameters: {'n_estimators': 899, 'learning_rate': 0.025799631869561225, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.7663473383810633, 'colsample_bytree': 0.7093860848602874, 'gamma': 1.2519556226616209, 'reg_alpha': 8.614787267850648, 'reg_lambda': 3.7619470844063123}. Best is trial 24 with value: 262.13453674316406.
[I 2026-10-02 18:37:47,116] Trial 26 finished with value: 262.81347274780273 and parameters: {'n_estimators': 1093, 'learning_rate': 0.06564701508786029, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.7593604201278576, 'colsample_bytree': 0.6917376778646737, 'gamma': 0.41819268460375014, 'reg_alpha': 2.4243027554984264, 'reg_lambda': 0.449396162362556}. Best is trial 24 with value: 262.13453674316406.
[I 2026-10-02 18:37:48,793] Trial 27 finished with value: 266.53491592407227 and parameters: {'n_estimators': 1305, 'learning_rate': 0.08654915002770329, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.7573872352891522, 'colsample_bytree': 0.6758988637188642, 'gamma': 0.34860539974132576, 'reg_alpha': 4.445706193630891, 'reg_lambda': 0.15281938931767725}. Best is trial 24 with value: 262.13453674316406.
[I 2026-10-02 18:37:51,919] Trial 28 finished with value: 298.0563621520996 and parameters: {'n_estimators': 1379, 'learning_rate': 0.03988324701140203, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.7684860848359609, 'colsample_bytree': 0.620296571737975, 'gamma': 0.6670602569703588, 'reg_alpha': 1.098647737436765, 'reg_lambda': 1.0109346407258195}. Best is trial 24 with value: 262.13453674316406.
[I 2026-10-02 18:37:53,805] Trial 29 finished with value: 276.1042594909668 and parameters: {'n_estimators': 1255, 'learning_rate': 0.05390088387525607, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.7216109123233583, 'colsample_bytree': 0.7324872954258969, 'gamma': 0.762113725255076, 'reg_alpha': 2.0580554396477386, 'reg_lambda': 0.48888509170639}. Best is trial 24 with value: 262.13453674316406.
[I 2026-10-02 18:37:55,202] Trial 30 finished with value: 274.0717239379883 and parameters: {'n_estimators': 954, 'learning_rate': 0.027642494420933746, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.7573839748954116, 'colsample_bytree': 0.6513894749636007, 'gamma': 1.055840298005163, 'reg_alpha': 7.756910860828593, 'reg_lambda': 0.7982648352230491}. Best is trial 24 with value: 262.13453674316406.
[I 2026-10-02 18:37:56,649] Trial 31 finished with value: 265.83206939697266 and parameters: {'n_estimators': 1091, 'learning_rate': 0.05067279716898259, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.8085379185632715, 'colsample_bytree': 0.6708103248164786, 'gamma': 0.8238575917720121, 'reg_alpha': 0.2585114898554339, 'reg_lambda': 2.328763240608655}. Best is trial 24 with value: 262.13453674316406.
[I 2026-10-02 18:37:58,065] Trial 32 finished with value: 263.5604782104492 and parameters: {'n_estimators': 1359, 'learning_rate': 0.06266994719481653, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.8343735639881691, 'colsample_bytree': 0.6004650856636075, 'gamma': 0.693310923369882, 'reg_alpha': 5.372756708268366, 'reg_lambda': 0.5855125082777737}. Best is trial 24 with value: 262.13453674316406.
[I 2026-10-02 18:37:59,601] Trial 33 finished with value: 273.47101974487305 and parameters: {'n_estimators': 1158, 'learning_rate': 0.05085897375933057, 'max_depth': 4, 'min_child_weight': 1, 'subsample': 0.7731591894017642, 'colsample_bytree': 0.6413097761450857, 'gamma': 0.897479731612476, 'reg_alpha': 0.3395018516855166, 'reg_lambda': 0.1909546732633828}. Best is trial 24 with value: 262.13453674316406.
[I 2026-10-02 18:38:01,172] Trial 34 finished with value: 277.58366775512695 and parameters: {'n_estimators': 1185, 'learning_rate': 0.04712577645005646, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.8518843021635093, 'colsample_bytree': 0.6795509747037229, 'gamma': 1.2828017197139387, 'reg_alpha': 3.6619448186196304, 'reg_lambda': 0.20647006287505335}. Best is trial 24 with value: 262.13453674316406.
[I 2026-10-02 18:38:02,936] Trial 35 finished with value: 277.6777648925781 and parameters: {'n_estimators': 1351, 'learning_rate': 0.05546886036836644, 'max_depth': 4, 'min_child_weight': 4, 'subsample': 0.8862520737019413, 'colsample_bytree': 0.6617704639773645, 'gamma': 0.8295788118455977, 'reg_alpha': 5.660226036813327, 'reg_lambda': 0.612305646005494}. Best is trial 24 with value: 262.13453674316406.
[I 2026-10-02 18:38:04,418] Trial 36 finished with value: 264.446720123291 and parameters: {'n_estimators': 1397, 'learning_rate': 0.05458514331604199, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.8545445634069812, 'colsample_bytree': 0.6212809819395235, 'gamma': 0.3925252420221581, 'reg_alpha': 1.6119748610364502, 'reg_lambda': 0.11350740023130527}. Best is trial 24 with value: 262.13453674316406.
[I 2026-10-02 18:38:05,918] Trial 37 finished with value: 262.36037826538086 and parameters: {'n_estimators': 1415, 'learning_rate': 0.03582741440063578, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.7667309267108207, 'colsample_bytree': 0.6112820680891913, 'gamma': 0.8080653322778373, 'reg_alpha': 0.929969696840967, 'reg_lambda': 0.16640941550022179}. Best is trial 24 with value: 262.13453674316406.
[I 2026-10-02 18:38:07,736] Trial 38 finished with value: 264.84886169433594 and parameters: {'n_estimators': 1281, 'learning_rate': 0.021923128548546226, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.6859675071415452, 'colsample_bytree': 0.6244666354557838, 'gamma': 1.6553423086392685, 'reg_alpha': 3.3185551728220073, 'reg_lambda': 0.340141044945033}. Best is trial 24 with value: 262.13453674316406.
[I 2026-10-02 18:38:09,990] Trial 39 finished with value: 263.1473197937012 and parameters: {'n_estimators': 1486, 'learning_rate': 0.030789325570494193, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.7953389408113893, 'colsample_bytree': 0.6989584422781538, 'gamma': 1.6781017346127238, 'reg_alpha': 0.15460840722900376, 'reg_lambda': 1.5585834758905763}. Best is trial 24 with value: 262.13453674316406.
[I 2026-10-02 18:38:11,909] Trial 40 finished with value: 263.7622604370117 and parameters: {'n_estimators': 1184, 'learning_rate': 0.041375019399849694, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.692934969043885, 'colsample_bytree': 0.7154674473670137, 'gamma': 0.27796911864047924, 'reg_alpha': 0.3998599011872987, 'reg_lambda': 1.3887407608849416}. Best is trial 24 with value: 262.13453674316406.
[I 2026-10-02 18:38:14,993] Trial 41 finished with value: 276.4077033996582 and parameters: {'n_estimators': 1220, 'learning_rate': 0.0300031807678001, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.7348539858739987, 'colsample_bytree': 0.6667840358798608, 'gamma': 0.3364940895183677, 'reg_alpha': 6.340755326497204, 'reg_lambda': 0.4003022296454011}. Best is trial 24 with value: 262.13453674316406.
[I 2026-10-02 18:38:17,987] Trial 42 finished with value: 273.8797378540039 and parameters: {'n_estimators': 1295, 'learning_rate': 0.02587805844650175, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.7691767572339093, 'colsample_bytree': 0.7276184333181965, 'gamma': 1.233591151551254, 'reg_alpha': 2.4371385985584184, 'reg_lambda': 0.300861362590959}. Best is trial 24 with value: 262.13453674316406.
[I 2026-10-02 18:38:21,048] Trial 43 finished with value: 277.44536209106445 and parameters: {'n_estimators': 1397, 'learning_rate': 0.04780370563552725, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.7320675086323981, 'colsample_bytree': 0.6505866995165211, 'gamma': 0.8330405312712892, 'reg_alpha': 2.313636224340859, 'reg_lambda': 0.46332435041065717}. Best is trial 24 with value: 262.13453674316406.
[I 2026-10-02 18:38:23,714] Trial 44 finished with value: 264.09993743896484 and parameters: {'n_estimators': 1226, 'learning_rate': 0.027964025806627532, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.6967580727978937, 'colsample_bytree': 0.6342720119348426, 'gamma': 0.8730994024810981, 'reg_alpha': 0.5475353859136145, 'reg_lambda': 0.5971017391950992}. Best is trial 24 with value: 262.13453674316406.
[I 2026-10-02 18:38:25,597] Trial 45 finished with value: 264.1237678527832 and parameters: {'n_estimators': 915, 'learning_rate': 0.06885731045400026, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.7462983354928356, 'colsample_bytree': 0.7593951729364763, 'gamma': 0.12169808480975286, 'reg_alpha': 1.0240719685278954, 'reg_lambda': 0.6436975727477378}. Best is trial 24 with value: 262.13453674316406.
[I 2026-10-02 18:38:28,191] Trial 46 finished with value: 260.6245918273926 and parameters: {'n_estimators': 1378, 'learning_rate': 0.030272461644948113, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.7681717569068932, 'colsample_bytree': 0.6461496884449351, 'gamma': 0.6891742600017476, 'reg_alpha': 0.9178643633724062, 'reg_lambda': 0.08951848423857388}. Best is trial 46 with value: 260.6245918273926.
[I 2026-10-02 18:38:30,928] Trial 47 finished with value: 266.7627067565918 and parameters: {'n_estimators': 1177, 'learning_rate': 0.01968743765488704, 'max_depth': 3, 'min_child_weight': 5, 'subsample': 0.756895459613159, 'colsample_bytree': 0.6265307982965215, 'gamma': 0.9401090380964994, 'reg_alpha': 0.2102469352755672, 'reg_lambda': 0.3245539193162332}. Best is trial 46 with value: 260.6245918273926.

In [8]:
print("Best CV RMSE:")
print(study.best_value)

print("\nBest parameters:")

for param, value in study.best_params.items():
    print(f"{param}: {value}")

Best CV RMSE:
260.5398941040039

Best parameters:
n_estimators: 1319
learning_rate: 0.031196340478036013
max_depth: 3
min_child_weight: 6
subsample: 0.7657530194390537
colsample_bytree: 0.6349189400332539
gamma: 1.600631021482472
reg_alpha: 0.8179299007457254
reg_lambda: 0.0875513743610601

In [9]:
best_params = study.best_params

seeds = [0, 1, 2, 3, 42]

results = []

for seed in seeds:

    model = xgb.XGBRegressor(
        **best_params,
        objective="reg:squarederror",
        random_state=seed,
        n_jobs=-1
    )

    model.fit(
        X_train,
        y_train
    )

    y_pred = model.predict(X_val)

    results.append({
        "Seed": seed,
        "RMSE": root_mean_squared_error(y_val, y_pred),
        "MSE": mean_squared_error(y_val, y_pred),
        "MAE": mean_absolute_error(y_val, y_pred),
        "MAPE": mean_absolute_percentage_error(y_val, y_pred),
        "R2": r2_score(y_val, y_pred)
    })

stability_df = pd.DataFrame(results)

stability_summary = stability_df.drop(
    columns="Seed"
).agg(["mean", "std", "min", "max"]).T

print("=== Results by seed ===")
display(stability_df)

print("\n=== Stability summary ===")
display(stability_summary)

=== Results by seed ===

   Seed        RMSE           MSE         MAE      MAPE        R2
0     0  161.711685  26150.669922  117.094360  0.055096  0.841711
1     1  161.825943  26187.636719  117.093147  0.055045  0.841487
2     2  161.207214  25987.763672  116.832954  0.054965  0.842697
3     3  160.559326  25779.296875  115.837906  0.054477  0.843959
4    42  161.324585  26025.621094  116.609688  0.054881  0.842468

=== Stability summary ===

              mean         std           min           max
RMSE    161.325751    0.500149    160.559326    161.825943
MSE   26026.197656  161.240050  25779.296875  26187.636719
MAE     116.693611    0.519355    115.837906    117.094360
MAPE      0.054893    0.000246      0.054477      0.055096
R2        0.842465    0.000976      0.841487      0.843959

In [10]:
stability_df.to_csv("../report/seed_weekly_first_harmonic_val_report.csv", index = False)
stability_summary.to_csv("../report/seed_summary_weekly_first_harmonic_val_report.csv", index = False)

# 4. Final Training on year 1 and year 2

In [11]:
df_train, df_test = build_features(
                                df_train = pd.read_excel("../Dataset/training.xlsx"), 
                                df_test = pd.read_excel("../Dataset/testing.xlsx")
                                   )

In [12]:
X_train = df_train[features]
y_train = df_train[target]

X_test = df_test[features]

In [13]:
print("Dataset sizes:")
print(f"Train (Year 1): {len(X_train):,}")
print(f"Validation (Year 2): {len(X_val):,}")
print(f"Test (Year 3): {len(X_test):,}")

Dataset sizes:
Train (Year 1): 17,544
Validation (Year 2): 8,760
Test (Year 3): 8,760

In [14]:
seeds = [0, 1, 2, 3, 42]

test_predictions = []

for seed in seeds:

    model = xgb.XGBRegressor(
        **best_params,
        objective="reg:squarederror",
        random_state=seed,
        n_jobs=-1
    )

    model.fit(
        X_train,
        y_train
    )

    pred = model.predict(X_test)

    test_predictions.append(pred)

y_test_pred = np.mean(
    test_predictions,
    axis=0
)

In [15]:
pd.DataFrame(y_test_pred).to_csv("../report/weekly_first_harmonic_test_prediction.csv", index = False)