# 1. Import Libraries

In [1]:
import sys
from pathlib import Path

# Thêm thư mục gốc (project root) vào Python path
project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

import pandas as pd
import xgboost as xgb

from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, mean_absolute_percentage_error, root_mean_squared_error

import numpy as np

from utils.features import build_features

import optuna

# 2. Load Dataset

In [2]:
df_train, df_val = build_features(
                                df_train = pd.read_excel("../Dataset/training.xlsx"), 
                                df_test = None,
                                pls_fit_years = [1]
                                   )

In [3]:
features = [
    'Year', 'Month', 'Day', 'Hour',
    'Combined_Temp',
    'Combined_GHI_1', 'Combined_GHI_2',
    'sin_day_k1', 'cos_day_k1',
    'sin_day_k2', 'cos_day_k2',
    'sin_week_k1', 'cos_week_k1',
]
target = 'Load'

# 3. Split Data

In [4]:
# Year 1 → TRAIN
train_mask = df_train['Year'] == 1

# Year 2 → VALIDATION
val_mask = df_val['Year'] == 2

# Year 3 → TEST
# Testing.xlsx is assumed to contain Year 3

X_train = df_train.loc[train_mask, features]
y_train = df_train.loc[train_mask, target]

X_val = df_val.loc[val_mask, features]
y_val = df_val.loc[val_mask, target]

print("Dataset sizes:")
print(f"Train (Year 1): {len(X_train):,}")
print(f"Validation (Year 2): {len(X_val):,}")

Dataset sizes:
Train (Year 1): 8,784
Validation (Year 2): 8,760

# 4. Train on year 1, evaluate on year 2

In [5]:
tscv = TimeSeriesSplit(n_splits=4)

In [6]:
def objective(trial):

    params = {
        "objective": "reg:squarederror",

        "n_estimators": trial.suggest_int(
            "n_estimators",
            100,
            1500
        ),

        "learning_rate": trial.suggest_float(
            "learning_rate",
            0.01,
            0.2,
            log=True
        ),

        "max_depth": trial.suggest_int(
            "max_depth",
            3,
            10
        ),

        "min_child_weight": trial.suggest_int(
            "min_child_weight",
            1,
            10
        ),

        "subsample": trial.suggest_float(
            "subsample",
            0.6,
            1.0
        ),

        "colsample_bytree": trial.suggest_float(
            "colsample_bytree",
            0.6,
            1.0
        ),

        "gamma": trial.suggest_float(
            "gamma",
            0,
            5
        ),

        "reg_alpha": trial.suggest_float(
            "reg_alpha",
            1e-8,
            10,
            log=True
        ),

        "reg_lambda": trial.suggest_float(
            "reg_lambda",
            1e-3,
            10,
            log=True
        ),

        "random_state": 42,
        "n_jobs": -1
    }

    fold_rmse = []

    # ============================================
    # Time-series CV trên YEAR 1
    # ============================================

    for train_idx, val_idx in tscv.split(X_train):

        X_fold_train = X_train.iloc[train_idx]
        X_fold_val = X_train.iloc[val_idx]

        y_fold_train = y_train.iloc[train_idx]
        y_fold_val = y_train.iloc[val_idx]

        model = xgb.XGBRegressor(**params)

        model.fit(
            X_fold_train,
            y_fold_train
        )

        y_pred = model.predict(
            X_fold_val
        )

        rmse = root_mean_squared_error(
            y_fold_val,
            y_pred
        )

        fold_rmse.append(rmse)

    # Optuna minimize mean CV RMSE
    return np.mean(fold_rmse)

In [7]:
study = optuna.create_study(
    direction="minimize",
    study_name="xgb_year1_timeseries_cv"
)

study.optimize(
    objective,
    n_trials=100,
    show_progress_bar=True
)

[I 2026-10-02 18:44:38,875] A new study created in memory with name: xgb_year1_timeseries_cv

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-10-02 18:44:42,211] Trial 0 finished with value: 298.40657806396484 and parameters: {'n_estimators': 1047, 'learning_rate': 0.0865965199582373, 'max_depth': 8, 'min_child_weight': 5, 'subsample': 0.8222118730347296, 'colsample_bytree': 0.7170433035970051, 'gamma': 3.916299657924619, 'reg_alpha': 0.17534762675261947, 'reg_lambda': 0.011241623262454207}. Best is trial 0 with value: 298.40657806396484.
[I 2026-10-02 18:44:44,619] Trial 1 finished with value: 279.416690826416 and parameters: {'n_estimators': 1293, 'learning_rate': 0.011551587496466223, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.887232058588332, 'colsample_bytree': 0.7943107250408034, 'gamma': 4.016646234326118, 'reg_alpha': 0.0016412894626760249, 'reg_lambda': 0.006077187730249041}. Best is trial 1 with value: 279.416690826416.
[I 2026-10-02 18:44:48,758] Trial 2 finished with value: 287.10847091674805 and parameters: {'n_estimators': 1398, 'learning_rate': 0.024926820123248806, 'max_depth': 8, 'min_child_weight': 10, 'subsample': 0.6758738482586003, 'colsample_bytree': 0.7799926714947578, 'gamma': 3.9178349218347575, 'reg_alpha': 0.08314676394139976, 'reg_lambda': 0.001463860670384165}. Best is trial 1 with value: 279.416690826416.
[I 2026-10-02 18:44:51,447] Trial 3 finished with value: 310.1234893798828 and parameters: {'n_estimators': 749, 'learning_rate': 0.15611326342621445, 'max_depth': 10, 'min_child_weight': 7, 'subsample': 0.6879179752575612, 'colsample_bytree': 0.6754566699761926, 'gamma': 3.3366277001269484, 'reg_alpha': 0.00021465176770014619, 'reg_lambda': 0.0778230963060454}. Best is trial 1 with value: 279.416690826416.
[I 2026-10-02 18:44:52,253] Trial 4 finished with value: 274.77881240844727 and parameters: {'n_estimators': 555, 'learning_rate': 0.027562222903496594, 'max_depth': 4, 'min_child_weight': 5, 'subsample': 0.608000184947021, 'colsample_bytree': 0.8374645416971449, 'gamma': 3.9864513396074064, 'reg_alpha': 0.0014071813488040943, 'reg_lambda': 0.05168316476023664}. Best is trial 4 with value: 274.77881240844727.
[I 2026-10-02 18:44:52,656] Trial 5 finished with value: 300.51612091064453 and parameters: {'n_estimators': 144, 'learning_rate': 0.03398253333621219, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.7620005129550101, 'colsample_bytree': 0.7303872216193567, 'gamma': 4.96548006302579, 'reg_alpha': 3.0713050999202325e-08, 'reg_lambda': 0.7988576383259332}. Best is trial 4 with value: 274.77881240844727.
[I 2026-10-02 18:44:53,823] Trial 6 finished with value: 271.7164764404297 and parameters: {'n_estimators': 982, 'learning_rate': 0.018243609447995416, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.8144310496601584, 'colsample_bytree': 0.7363859052826294, 'gamma': 2.321112264833143, 'reg_alpha': 3.7475511987240934e-06, 'reg_lambda': 0.05113423400509046}. Best is trial 6 with value: 271.7164764404297.
[I 2026-10-02 18:44:56,364] Trial 7 finished with value: 280.4596481323242 and parameters: {'n_estimators': 1453, 'learning_rate': 0.02505784605499004, 'max_depth': 5, 'min_child_weight': 8, 'subsample': 0.9547078638095625, 'colsample_bytree': 0.9156838431990206, 'gamma': 1.2869351505080595, 'reg_alpha': 0.1014314442410509, 'reg_lambda': 0.0031537353545227245}. Best is trial 6 with value: 271.7164764404297.
[I 2026-10-02 18:44:57,404] Trial 8 finished with value: 272.3285789489746 and parameters: {'n_estimators': 833, 'learning_rate': 0.021462247743673963, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.6702899026787477, 'colsample_bytree': 0.7115540964320907, 'gamma': 0.6147365933707699, 'reg_alpha': 0.0014169946339409726, 'reg_lambda': 4.5263355564407455}. Best is trial 6 with value: 271.7164764404297.
[I 2026-10-02 18:44:57,868] Trial 9 finished with value: 324.4091567993164 and parameters: {'n_estimators': 208, 'learning_rate': 0.01545254344036724, 'max_depth': 3, 'min_child_weight': 5, 'subsample': 0.7422705983932374, 'colsample_bytree': 0.760910855165265, 'gamma': 1.0550584376267929, 'reg_alpha': 6.2874861671291825e-06, 'reg_lambda': 0.8709557792083019}. Best is trial 6 with value: 271.7164764404297.
[I 2026-10-02 18:44:58,696] Trial 10 finished with value: 290.5861701965332 and parameters: {'n_estimators': 571, 'learning_rate': 0.016940326481481787, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.9289442457574566, 'colsample_bytree': 0.6640203755524742, 'gamma': 1.8404314378970703, 'reg_alpha': 2.424683909488333e-06, 'reg_lambda': 0.12696797419069955}. Best is trial 6 with value: 271.7164764404297.
[I 2026-10-02 18:45:00,506] Trial 11 finished with value: 285.1085319519043 and parameters: {'n_estimators': 718, 'learning_rate': 0.022555700381457357, 'max_depth': 5, 'min_child_weight': 7, 'subsample': 0.7547194345927529, 'colsample_bytree': 0.7287916365114377, 'gamma': 1.77017404317895, 'reg_alpha': 0.012476453884820124, 'reg_lambda': 0.022392066419839787}. Best is trial 6 with value: 271.7164764404297.
[I 2026-10-02 18:45:01,322] Trial 12 finished with value: 270.02219009399414 and parameters: {'n_estimators': 518, 'learning_rate': 0.05013437108602804, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.6723097616201819, 'colsample_bytree': 0.6627291046092461, 'gamma': 1.4408211250025424, 'reg_alpha': 0.0002752848835446791, 'reg_lambda': 2.6428975877361}. Best is trial 12 with value: 270.02219009399414.
[I 2026-10-02 18:45:01,784] Trial 13 finished with value: 274.51718521118164 and parameters: {'n_estimators': 250, 'learning_rate': 0.09700017894039603, 'max_depth': 4, 'min_child_weight': 7, 'subsample': 0.7446744521467628, 'colsample_bytree': 0.7441350935047265, 'gamma': 1.4649179536979817, 'reg_alpha': 0.0028899451216327105, 'reg_lambda': 0.42008752107107084}. Best is trial 12 with value: 270.02219009399414.
[I 2026-10-02 18:45:02,681] Trial 14 finished with value: 266.93053436279297 and parameters: {'n_estimators': 695, 'learning_rate': 0.04046098203395189, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.6307066538204888, 'colsample_bytree': 0.7144556322899359, 'gamma': 2.302323828678256, 'reg_alpha': 5.0557703624510453e-05, 'reg_lambda': 0.03139308945940732}. Best is trial 14 with value: 266.93053436279297.
[I 2026-10-02 18:45:03,471] Trial 15 finished with value: 289.1100196838379 and parameters: {'n_estimators': 516, 'learning_rate': 0.02434412420258637, 'max_depth': 4, 'min_child_weight': 6, 'subsample': 0.6276133376426611, 'colsample_bytree': 0.6145498489826827, 'gamma': 2.151718637760315, 'reg_alpha': 0.0007665898467982002, 'reg_lambda': 5.071096991175448}. Best is trial 14 with value: 266.93053436279297.
[I 2026-10-02 18:45:04,139] Trial 16 finished with value: 271.59870529174805 and parameters: {'n_estimators': 538, 'learning_rate': 0.02682953689141404, 'max_depth': 3, 'min_child_weight': 10, 'subsample': 0.6104904663644924, 'colsample_bytree': 0.7034371060223259, 'gamma': 1.9191915218129285, 'reg_alpha': 1.2695270499001565e-07, 'reg_lambda': 0.4863896573935017}. Best is trial 14 with value: 266.93053436279297.
[I 2026-10-02 18:45:04,968] Trial 17 finished with value: 264.2399673461914 and parameters: {'n_estimators': 685, 'learning_rate': 0.07426823372205353, 'max_depth': 3, 'min_child_weight': 10, 'subsample': 0.6941390792837145, 'colsample_bytree': 0.6318084441298089, 'gamma': 1.7177353649670626, 'reg_alpha': 0.0008498629307175033, 'reg_lambda': 0.07240743703669968}. Best is trial 17 with value: 264.2399673461914.
[I 2026-10-02 18:45:05,868] Trial 18 finished with value: 275.64838790893555 and parameters: {'n_estimators': 548, 'learning_rate': 0.03891839617716848, 'max_depth': 4, 'min_child_weight': 5, 'subsample': 0.6566701346385039, 'colsample_bytree': 0.7449261772233368, 'gamma': 2.213749000455385, 'reg_alpha': 0.0005637413213262357, 'reg_lambda': 0.026515590819013734}. Best is trial 17 with value: 264.2399673461914.
[I 2026-10-02 18:45:06,802] Trial 19 finished with value: 273.7700729370117 and parameters: {'n_estimators': 579, 'learning_rate': 0.0559454348875153, 'max_depth': 4, 'min_child_weight': 9, 'subsample': 0.6853838999985725, 'colsample_bytree': 0.7121419992480267, 'gamma': 3.0627143282363063, 'reg_alpha': 0.048795582823202586, 'reg_lambda': 0.013897726450605658}. Best is trial 17 with value: 264.2399673461914.
[I 2026-10-02 18:45:07,872] Trial 20 finished with value: 285.3975639343262 and parameters: {'n_estimators': 747, 'learning_rate': 0.10724760548519308, 'max_depth': 4, 'min_child_weight': 9, 'subsample': 0.7701765947648966, 'colsample_bytree': 0.670003910340575, 'gamma': 1.6039211826214297, 'reg_alpha': 5.991199188679164e-05, 'reg_lambda': 0.07040493877945345}. Best is trial 17 with value: 264.2399673461914.
[I 2026-10-02 18:45:08,781] Trial 21 finished with value: 264.2203826904297 and parameters: {'n_estimators': 764, 'learning_rate': 0.05605716986463226, 'max_depth': 3, 'min_child_weight': 9, 'subsample': 0.7141285414027864, 'colsample_bytree': 0.6530985385092855, 'gamma': 3.0175857722097224, 'reg_alpha': 9.996486470337392e-05, 'reg_lambda': 0.002457514589695403}. Best is trial 21 with value: 264.2203826904297.
[I 2026-10-02 18:45:09,769] Trial 22 finished with value: 262.1400375366211 and parameters: {'n_estimators': 807, 'learning_rate': 0.05423364722319992, 'max_depth': 3, 'min_child_weight': 9, 'subsample': 0.6626948980993299, 'colsample_bytree': 0.610418178981063, 'gamma': 3.5784198122346345, 'reg_alpha': 5.686294080165958e-06, 'reg_lambda': 0.006769107898816605}. Best is trial 22 with value: 262.1400375366211.
[I 2026-10-02 18:45:10,739] Trial 23 finished with value: 276.4554901123047 and parameters: {'n_estimators': 606, 'learning_rate': 0.04769227600445079, 'max_depth': 4, 'min_child_weight': 9, 'subsample': 0.6999531108985632, 'colsample_bytree': 0.6458211490571483, 'gamma': 3.4422013532148736, 'reg_alpha': 4.235724138021115e-06, 'reg_lambda': 0.0032319030107020997}. Best is trial 22 with value: 262.1400375366211.
[I 2026-10-02 18:45:11,578] Trial 24 finished with value: 264.4951286315918 and parameters: {'n_estimators': 748, 'learning_rate': 0.0505421942821031, 'max_depth': 3, 'min_child_weight': 9, 'subsample': 0.6372747583848566, 'colsample_bytree': 0.6454171945292239, 'gamma': 4.552372410583907, 'reg_alpha': 0.00017724763100866828, 'reg_lambda': 0.0011363671778406208}. Best is trial 22 with value: 262.1400375366211.
[I 2026-10-02 18:45:12,611] Trial 25 finished with value: 268.6042175292969 and parameters: {'n_estimators': 935, 'learning_rate': 0.023463175657373908, 'max_depth': 3, 'min_child_weight': 9, 'subsample': 0.6195952381708728, 'colsample_bytree': 0.6347163731145354, 'gamma': 2.914068939754573, 'reg_alpha': 8.074588823453799e-07, 'reg_lambda': 0.005664711295668355}. Best is trial 22 with value: 262.1400375366211.
[I 2026-10-02 18:45:13,809] Trial 26 finished with value: 280.81238555908203 and parameters: {'n_estimators': 918, 'learning_rate': 0.08659332898398708, 'max_depth': 4, 'min_child_weight': 9, 'subsample': 0.7275643329717238, 'colsample_bytree': 0.6078810244960765, 'gamma': 1.087206099452954, 'reg_alpha': 0.006889077876945214, 'reg_lambda': 0.013510491573014538}. Best is trial 22 with value: 262.1400375366211.
[I 2026-10-02 18:45:15,175] Trial 27 finished with value: 275.210262298584 and parameters: {'n_estimators': 992, 'learning_rate': 0.05305435706901144, 'max_depth': 4, 'min_child_weight': 10, 'subsample': 0.6412922212600116, 'colsample_bytree': 0.6314949039865508, 'gamma': 3.6332670166579177, 'reg_alpha': 0.0004300886943842303, 'reg_lambda': 0.005981534378638317}. Best is trial 22 with value: 262.1400375366211.
[I 2026-10-02 18:45:16,132] Trial 28 finished with value: 264.6377182006836 and parameters: {'n_estimators': 787, 'learning_rate': 0.059018976124107246, 'max_depth': 3, 'min_child_weight': 10, 'subsample': 0.6165517759650205, 'colsample_bytree': 0.6569700428915579, 'gamma': 1.147012253549462, 'reg_alpha': 0.0007592463728286106, 'reg_lambda': 0.023373077637282812}. Best is trial 22 with value: 262.1400375366211.
[I 2026-10-02 18:45:16,964] Trial 29 finished with value: 264.69455337524414 and parameters: {'n_estimators': 687, 'learning_rate': 0.07027755871671997, 'max_depth': 3, 'min_child_weight': 9, 'subsample': 0.7301461757090383, 'colsample_bytree': 0.7320357122321494, 'gamma': 3.5581657792099106, 'reg_alpha': 3.488950129094409e-06, 'reg_lambda': 0.018240895303257437}. Best is trial 22 with value: 262.1400375366211.
[I 2026-10-02 18:45:17,739] Trial 30 finished with value: 264.5038604736328 and parameters: {'n_estimators': 601, 'learning_rate': 0.0829026755002636, 'max_depth': 3, 'min_child_weight': 10, 'subsample': 0.7064191742210427, 'colsample_bytree': 0.6004598858899711, 'gamma': 4.035042600400506, 'reg_alpha': 4.330964325123826e-07, 'reg_lambda': 0.0024917655243236287}. Best is trial 22 with value: 262.1400375366211.
[I 2026-10-02 18:45:18,561] Trial 31 finished with value: 262.3408508300781 and parameters: {'n_estimators': 688, 'learning_rate': 0.061207439091972654, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.6730032221550081, 'colsample_bytree': 0.6219888531563372, 'gamma': 3.3872130962766622, 'reg_alpha': 8.894950975106218e-05, 'reg_lambda': 0.005643877378746747}. Best is trial 22 with value: 262.1400375366211.
[I 2026-10-02 18:45:19,707] Trial 32 finished with value: 263.5336265563965 and parameters: {'n_estimators': 891, 'learning_rate': 0.05990978548079082, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.6342743183325081, 'colsample_bytree': 0.654431364091261, 'gamma': 3.849638245429678, 'reg_alpha': 6.65910440715188e-06, 'reg_lambda': 0.004487607647418475}. Best is trial 22 with value: 262.1400375366211.
[I 2026-10-02 18:45:20,795] Trial 33 finished with value: 265.07284927368164 and parameters: {'n_estimators': 936, 'learning_rate': 0.04088204968054036, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.6513597755236805, 'colsample_bytree': 0.6709719093470525, 'gamma': 2.98016898932294, 'reg_alpha': 0.00017881225923342326, 'reg_lambda': 0.014078624245605582}. Best is trial 22 with value: 262.1400375366211.
[I 2026-10-02 18:45:21,668] Trial 34 finished with value: 263.5796890258789 and parameters: {'n_estimators': 689, 'learning_rate': 0.07007479688503493, 'max_depth': 3, 'min_child_weight': 9, 'subsample': 0.6934079052780358, 'colsample_bytree': 0.6682583988939974, 'gamma': 3.106806390473158, 'reg_alpha': 0.0015823871331064408, 'reg_lambda': 0.0018474534664892337}. Best is trial 22 with value: 262.1400375366211.
[I 2026-10-02 18:45:22,747] Trial 35 finished with value: 272.9049987792969 and parameters: {'n_estimators': 748, 'learning_rate': 0.053565746973100827, 'max_depth': 4, 'min_child_weight': 9, 'subsample': 0.6264022515452673, 'colsample_bytree': 0.6444401205544988, 'gamma': 3.509796615840696, 'reg_alpha': 5.586007183315678e-06, 'reg_lambda': 0.03196122168103175}. Best is trial 22 with value: 262.1400375366211.
[I 2026-10-02 18:45:23,875] Trial 36 finished with value: 276.6214790344238 and parameters: {'n_estimators': 766, 'learning_rate': 0.05237241064656188, 'max_depth': 4, 'min_child_weight': 8, 'subsample': 0.6773669723059099, 'colsample_bytree': 0.6563584505675356, 'gamma': 4.1392140177724634, 'reg_alpha': 2.537387166043513e-05, 'reg_lambda': 0.014120713091209826}. Best is trial 22 with value: 262.1400375366211.
[I 2026-10-02 18:45:25,343] Trial 37 finished with value: 264.69451904296875 and parameters: {'n_estimators': 1144, 'learning_rate': 0.06293364889099895, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.6255210041180866, 'colsample_bytree': 0.6779620349347639, 'gamma': 4.636044731257895, 'reg_alpha': 1.3326033805925096e-06, 'reg_lambda': 0.002847900317213942}. Best is trial 22 with value: 262.1400375366211.
[I 2026-10-02 18:45:26,426] Trial 38 finished with value: 265.3443717956543 and parameters: {'n_estimators': 849, 'learning_rate': 0.08067550528168024, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.676939596258331, 'colsample_bytree': 0.6138221790217848, 'gamma': 4.430345708577391, 'reg_alpha': 0.00029574711850859867, 'reg_lambda': 0.022720146587956135}. Best is trial 22 with value: 262.1400375366211.
[I 2026-10-02 18:45:27,671] Trial 39 finished with value: 266.0762519836426 and parameters: {'n_estimators': 811, 'learning_rate': 0.034377763833982077, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.680357877714554, 'colsample_bytree': 0.6801182293251149, 'gamma': 3.912109511682472, 'reg_alpha': 1.8519937424141108e-06, 'reg_lambda': 0.01772979042558638}. Best is trial 22 with value: 262.1400375366211.
[I 2026-10-02 18:45:28,461] Trial 40 finished with value: 266.18871688842773 and parameters: {'n_estimators': 629, 'learning_rate': 0.07953415902009302, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.6325776322341431, 'colsample_bytree': 0.6426274255298373, 'gamma': 2.7964529275409578, 'reg_alpha': 8.578469735992721e-05, 'reg_lambda': 0.011912240100516188}. Best is trial 22 with value: 262.1400375366211.
[I 2026-10-02 18:45:29,421] Trial 41 finished with value: 263.64824295043945 and parameters: {'n_estimators': 700, 'learning_rate': 0.05248814366142944, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.6554330807194471, 'colsample_bytree': 0.606471779177419, 'gamma': 3.138710009694342, 'reg_alpha': 0.001192199055319948, 'reg_lambda': 0.002018922523792167}. Best is trial 22 with value: 262.1400375366211.
[I 2026-10-02 18:45:30,405] Trial 42 finished with value: 263.1859474182129 and parameters: {'n_estimators': 724, 'learning_rate': 0.06561536788071642, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.7218153484602254, 'colsample_bytree': 0.6914920999117202, 'gamma': 3.5681645556024546, 'reg_alpha': 0.0006182766699851794, 'reg_lambda': 0.0016105730074460914}. Best is trial 22 with value: 262.1400375366211.
[I 2026-10-02 18:45:31,601] Trial 43 finished with value: 261.75481033325195 and parameters: {'n_estimators': 979, 'learning_rate': 0.0882226162790485, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.6952035117644266, 'colsample_bytree': 0.637956507617659, 'gamma': 3.489347383167597, 'reg_alpha': 6.500590010701007e-06, 'reg_lambda': 0.0033822795524953582}. Best is trial 43 with value: 261.75481033325195.
[I 2026-10-02 18:45:32,775] Trial 44 finished with value: 261.48948669433594 and parameters: {'n_estimators': 1031, 'learning_rate': 0.061132894925082865, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.6296555328420649, 'colsample_bytree': 0.6173557367841179, 'gamma': 4.434906553095939, 'reg_alpha': 5.357887769202991e-06, 'reg_lambda': 0.004149303933911897}. Best is trial 44 with value: 261.48948669433594.
[I 2026-10-02 18:45:33,801] Trial 45 finished with value: 262.9816093444824 and parameters: {'n_estimators': 805, 'learning_rate': 0.08565752665325907, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.6538510865102853, 'colsample_bytree': 0.6134696173711853, 'gamma': 3.426962391353198, 'reg_alpha': 0.00048248617555441027, 'reg_lambda': 0.004933247049504941}. Best is trial 44 with value: 261.48948669433594.
[I 2026-10-02 18:45:34,739] Trial 46 finished with value: 277.9525566101074 and parameters: {'n_estimators': 727, 'learning_rate': 0.061830915347700625, 'max_depth': 4, 'min_child_weight': 9, 'subsample': 0.6944219475243562, 'colsample_bytree': 0.6099562955268863, 'gamma': 3.793841058995863, 'reg_alpha': 5.746166709716397e-06, 'reg_lambda': 0.009713696167541098}. Best is trial 44 with value: 261.48948669433594.
[I 2026-10-02 18:45:35,741] Trial 47 finished with value: 265.7060356140137 and parameters: {'n_estimators': 723, 'learning_rate': 0.07214255762828246, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.6264673172828926, 'colsample_bytree': 0.6497202404393998, 'gamma': 2.864256581411889, 'reg_alpha': 4.001413157958856e-06, 'reg_lambda': 0.02197495771536119}. Best is trial 44 with value: 261.48948669433594.

In [8]:
print("Best CV RMSE:")
print(study.best_value)

print("\nBest parameters:")

for param, value in study.best_params.items():
    print(f"{param}: {value}")

Best CV RMSE:
258.60409927368164

Best parameters:
n_estimators: 1064
learning_rate: 0.06292531041929814
max_depth: 3
min_child_weight: 7
subsample: 0.6424403066647434
colsample_bytree: 0.648748536282336
gamma: 4.180675000275074
reg_alpha: 3.6851039306954485e-06
reg_lambda: 0.0016090619993514859

In [9]:
best_params = study.best_params

seeds = [0, 1, 2, 3, 42]

results = []

for seed in seeds:

    model = xgb.XGBRegressor(
        **best_params,
        objective="reg:squarederror",
        random_state=seed,
        n_jobs=-1
    )

    model.fit(
        X_train,
        y_train
    )

    y_pred = model.predict(X_val)

    results.append({
        "Seed": seed,
        "RMSE": root_mean_squared_error(y_val, y_pred),
        "MSE": mean_squared_error(y_val, y_pred),
        "MAE": mean_absolute_error(y_val, y_pred),
        "MAPE": mean_absolute_percentage_error(y_val, y_pred),
        "R2": r2_score(y_val, y_pred)
    })

stability_df = pd.DataFrame(results)

stability_summary = stability_df.drop(
    columns="Seed"
).agg(["mean", "std", "min", "max"]).T

print("=== Results by seed ===")
display(stability_df)

print("\n=== Stability summary ===")
display(stability_summary)

=== Results by seed ===

   Seed        RMSE           MSE         MAE      MAPE        R2
0     0  159.434525  25419.365234  115.260513  0.054273  0.846138
1     1  160.490601  25757.234375  115.878036  0.054505  0.844093
2     2  160.900787  25889.064453  116.208023  0.054677  0.843295
3     3  159.959549  25587.056641  115.620773  0.054448  0.845123
4    42  162.288437  26337.537109  117.828964  0.055498  0.840580

=== Stability summary ===

              mean         std           min           max
RMSE    160.614780    1.086356    159.434525    162.288437
MSE   25798.051563  349.612727  25419.365234  26337.537109
MAE     116.159262    0.995878    115.260513    117.828964
MAPE      0.054680    0.000480      0.054273      0.055498
R2        0.843846    0.002116      0.840580      0.846138

In [10]:
stability_df.to_csv("../report/seed_daily_second_harmonic_val_report.csv", index = False)
stability_summary.to_csv("../report/seed_summary_daily_second_harmonic_val_report.csv", index = False)

# 4. Final Training on year 1 and year 2

In [11]:
df_train, df_test = build_features(
                                df_train = pd.read_excel("../Dataset/training.xlsx"), 
                                df_test = pd.read_excel("../Dataset/testing.xlsx")
                                   )

In [12]:
X_train = df_train[features]
y_train = df_train[target]

X_test = df_test[features]

In [13]:
print("Dataset sizes:")
print(f"Train (Year 1): {len(X_train):,}")
print(f"Validation (Year 2): {len(X_val):,}")
print(f"Test (Year 3): {len(X_test):,}")

Dataset sizes:
Train (Year 1): 17,544
Validation (Year 2): 8,760
Test (Year 3): 8,760

In [14]:
seeds = [0, 1, 2, 3, 42]

test_predictions = []

for seed in seeds:

    model = xgb.XGBRegressor(
        **best_params,
        objective="reg:squarederror",
        random_state=seed,
        n_jobs=-1
    )

    model.fit(
        X_train,
        y_train
    )

    pred = model.predict(X_test)

    test_predictions.append(pred)

y_test_pred = np.mean(
    test_predictions,
    axis=0
)

In [15]:
pd.DataFrame(y_test_pred).to_csv("../report/daily_second_harmonic_test_prediction.csv", index = False)