# 1. Import Libraries

In [1]:
import sys
from pathlib import Path

# Thêm thư mục gốc (project root) vào Python path
project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

import pandas as pd
import xgboost as xgb

from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, mean_absolute_percentage_error, root_mean_squared_error

import numpy as np

from utils.features import build_features

import optuna

# 2. Load Dataset

In [2]:
df_train, df_val = build_features(
                                df_train = pd.read_excel("../Dataset/training.xlsx"), 
                                df_test = None,
                                pls_fit_years = [1]
                                   )

In [3]:
features = [
    'Year', 'Month', 'Day', 'Hour',
    'Combined_Temp',
    'Combined_GHI_1', 'Combined_GHI_2',
    'sin_day_k1', 'cos_day_k1',
    'sin_day_k2', 'cos_day_k2',
    'sin_week_k1', 'cos_week_k1',
    'dow',
    'lag_1_temp', 'lag_1_ghi_1', 'lag_1_ghi_2',
    'delta_1_temp', 'delta_1_ghi_1', 'delta_1_ghi_2',
    'delta_24_temp', 'delta_24_ghi_1', 'delta_24_ghi_2'
]
target = 'Load'

# 3. Split Data

In [4]:
# Year 1 → TRAIN
train_mask = df_train['Year'] == 1

# Year 2 → VALIDATION
val_mask = df_val['Year'] == 2

# Year 3 → TEST
# Testing.xlsx is assumed to contain Year 3

X_train = df_train.loc[train_mask, features]
y_train = df_train.loc[train_mask, target]

X_val = df_val.loc[val_mask, features]
y_val = df_val.loc[val_mask, target]

print("Dataset sizes:")
print(f"Train (Year 1): {len(X_train):,}")
print(f"Validation (Year 2): {len(X_val):,}")

Dataset sizes:
Train (Year 1): 8,784
Validation (Year 2): 8,760

# 4. Train on year 1, evaluate on year 2

In [5]:
tscv = TimeSeriesSplit(n_splits=4)

In [6]:
def objective(trial):

    params = {
        "objective": "reg:squarederror",

        "n_estimators": trial.suggest_int(
            "n_estimators",
            100,
            1500
        ),

        "learning_rate": trial.suggest_float(
            "learning_rate",
            0.01,
            0.2,
            log=True
        ),

        "max_depth": trial.suggest_int(
            "max_depth",
            3,
            10
        ),

        "min_child_weight": trial.suggest_int(
            "min_child_weight",
            1,
            10
        ),

        "subsample": trial.suggest_float(
            "subsample",
            0.6,
            1.0
        ),

        "colsample_bytree": trial.suggest_float(
            "colsample_bytree",
            0.6,
            1.0
        ),

        "gamma": trial.suggest_float(
            "gamma",
            0,
            5
        ),

        "reg_alpha": trial.suggest_float(
            "reg_alpha",
            1e-8,
            10,
            log=True
        ),

        "reg_lambda": trial.suggest_float(
            "reg_lambda",
            1e-3,
            10,
            log=True
        ),

        "random_state": 42,
        "n_jobs": -1
    }

    fold_rmse = []

    # ============================================
    # Time-series CV trên YEAR 1
    # ============================================

    for train_idx, val_idx in tscv.split(X_train):

        X_fold_train = X_train.iloc[train_idx]
        X_fold_val = X_train.iloc[val_idx]

        y_fold_train = y_train.iloc[train_idx]
        y_fold_val = y_train.iloc[val_idx]

        model = xgb.XGBRegressor(**params)

        model.fit(
            X_fold_train,
            y_fold_train
        )

        y_pred = model.predict(
            X_fold_val
        )

        rmse = root_mean_squared_error(
            y_fold_val,
            y_pred
        )

        fold_rmse.append(rmse)

    # Optuna minimize mean CV RMSE
    return np.mean(fold_rmse)

In [7]:
sampler = optuna.samplers.TPESampler(seed=42)

study = optuna.create_study(
    direction="minimize",
    study_name="xgb_year1_timeseries_cv",
    sampler=sampler
)

study.optimize(
    objective,
    n_trials=100,
    show_progress_bar=True
)

[I 2026-10-02 19:05:53,582] A new study created in memory with name: xgb_year1_timeseries_cv

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-10-02 19:05:58,479] Trial 0 finished with value: 265.99280166625977 and parameters: {'n_estimators': 624, 'learning_rate': 0.17254716573280354, 'max_depth': 8, 'min_child_weight': 6, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.662397808134481, 'gamma': 0.2904180608409973, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 0.2537815508265665}. Best is trial 0 with value: 265.99280166625977.
[I 2026-10-02 19:06:05,194] Trial 1 finished with value: 260.1857109069824 and parameters: {'n_estimators': 1092, 'learning_rate': 0.010636066512540286, 'max_depth': 10, 'min_child_weight': 9, 'subsample': 0.6849356442713105, 'colsample_bytree': 0.6727299868828402, 'gamma': 0.9170225492671691, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.12561043700013558}. Best is trial 1 with value: 260.1857109069824.
[I 2026-10-02 19:06:08,824] Trial 2 finished with value: 267.50529861450195 and parameters: {'n_estimators': 705, 'learning_rate': 0.023927528765580644, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7168578594140873, 'colsample_bytree': 0.7465447373174767, 'gamma': 2.28034992108518, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 0.006290644294586149}. Best is trial 1 with value: 260.1857109069824.
[I 2026-10-02 19:06:10,151] Trial 3 finished with value: 250.63692474365234 and parameters: {'n_estimators': 820, 'learning_rate': 0.05898602410432694, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.6682096494749166, 'colsample_bytree': 0.6260206371941118, 'gamma': 4.7444276862666666, 'reg_alpha': 4.905556676028774, 'reg_lambda': 1.7123375973163988}. Best is trial 3 with value: 250.63692474365234.
[I 2026-10-02 19:06:13,213] Trial 4 finished with value: 263.0567054748535 and parameters: {'n_estimators': 526, 'learning_rate': 0.013399060561509796, 'max_depth': 8, 'min_child_weight': 5, 'subsample': 0.6488152939379115, 'colsample_bytree': 0.798070764044508, 'gamma': 0.17194260557609198, 'reg_alpha': 1.527156759251193, 'reg_lambda': 0.010842262717330166}. Best is trial 3 with value: 250.63692474365234.
[I 2026-10-02 19:06:17,801] Trial 5 finished with value: 265.5346984863281 and parameters: {'n_estimators': 1028, 'learning_rate': 0.02544166090938368, 'max_depth': 7, 'min_child_weight': 6, 'subsample': 0.6739417822102108, 'colsample_bytree': 0.9878338511058234, 'gamma': 3.8756641168055728, 'reg_alpha': 2.854239907497756, 'reg_lambda': 3.7958531426706403}. Best is trial 3 with value: 250.63692474365234.
[I 2026-10-02 19:06:19,469] Trial 6 finished with value: 249.6109275817871 and parameters: {'n_estimators': 937, 'learning_rate': 0.15826541904647565, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.6180909155642152, 'colsample_bytree': 0.7301321323053057, 'gamma': 1.9433864484474102, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 2.0651425578959257}. Best is trial 6 with value: 249.6109275817871.
[I 2026-10-02 19:06:22,428] Trial 7 finished with value: 272.6033744812012 and parameters: {'n_estimators': 599, 'learning_rate': 0.023200867504756827, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.9208787923016158, 'colsample_bytree': 0.6298202574719083, 'gamma': 4.9344346830025865, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 0.0062353771356731605}. Best is trial 6 with value: 249.6109275817871.
[I 2026-10-02 19:06:23,103] Trial 8 finished with value: 272.1806411743164 and parameters: {'n_estimators': 107, 'learning_rate': 0.11506408247250169, 'max_depth': 8, 'min_child_weight': 8, 'subsample': 0.9085081386743783, 'colsample_bytree': 0.6296178606936361, 'gamma': 1.7923286427213632, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 2.8340904295147746}. Best is trial 6 with value: 249.6109275817871.
[I 2026-10-02 19:06:24,896] Trial 9 finished with value: 251.81767654418945 and parameters: {'n_estimators': 973, 'learning_rate': 0.026946865572417687, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.7300733288106989, 'colsample_bytree': 0.8918424713352255, 'gamma': 3.1877873567760657, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.0774211647399625}. Best is trial 6 with value: 249.6109275817871.
[I 2026-10-02 19:06:27,117] Trial 10 finished with value: 260.31894302368164 and parameters: {'n_estimators': 1033, 'learning_rate': 0.02589170963782682, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.9542625333911193, 'colsample_bytree': 0.7245381339258192, 'gamma': 1.9647134840779568, 'reg_alpha': 1.3232991168593193e-05, 'reg_lambda': 0.25664762423103704}. Best is trial 6 with value: 249.6109275817871.
[I 2026-10-02 19:06:28,669] Trial 11 finished with value: 247.93255996704102 and parameters: {'n_estimators': 921, 'learning_rate': 0.07213961138571867, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.6793460058873315, 'colsample_bytree': 0.7143535352216754, 'gamma': 2.3892882010593666, 'reg_alpha': 3.626894257930167e-05, 'reg_lambda': 3.3969620574636195}. Best is trial 11 with value: 247.93255996704102.
[I 2026-10-02 19:06:31,082] Trial 12 finished with value: 264.6165199279785 and parameters: {'n_estimators': 1098, 'learning_rate': 0.14801892424071553, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.6488125587121697, 'colsample_bytree': 0.7682903039370277, 'gamma': 2.897206277386939, 'reg_alpha': 3.144272175248195e-06, 'reg_lambda': 8.48882806257455}. Best is trial 11 with value: 247.93255996704102.
[I 2026-10-02 19:06:32,262] Trial 13 finished with value: 252.00280380249023 and parameters: {'n_estimators': 659, 'learning_rate': 0.06036679196949417, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.6412245229092012, 'colsample_bytree': 0.6495822196197948, 'gamma': 1.3424127310533318, 'reg_alpha': 1.9166868665767748e-05, 'reg_lambda': 2.2780066416530316}. Best is trial 11 with value: 247.93255996704102.
[I 2026-10-02 19:06:34,412] Trial 14 finished with value: 246.97655487060547 and parameters: {'n_estimators': 1273, 'learning_rate': 0.12453048774079262, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.7147361448251353, 'colsample_bytree': 0.6528126303763173, 'gamma': 1.418793277811988, 'reg_alpha': 1.2293800000484688e-06, 'reg_lambda': 4.080480879972947}. Best is trial 14 with value: 246.97655487060547.
[I 2026-10-02 19:06:36,543] Trial 15 finished with value: 254.52738189697266 and parameters: {'n_estimators': 1300, 'learning_rate': 0.14758465580979674, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.662777504513111, 'colsample_bytree': 0.6250665600407576, 'gamma': 2.1947766211464064, 'reg_alpha': 2.2225322668930265e-07, 'reg_lambda': 1.640107549221917}. Best is trial 14 with value: 246.97655487060547.
[I 2026-10-02 19:06:38,974] Trial 16 finished with value: 255.39527130126953 and parameters: {'n_estimators': 1170, 'learning_rate': 0.06649138488473445, 'max_depth': 4, 'min_child_weight': 4, 'subsample': 0.7089932825843575, 'colsample_bytree': 0.6667970546335195, 'gamma': 2.441749657481433, 'reg_alpha': 2.2638232612467757e-06, 'reg_lambda': 0.7714459196751967}. Best is trial 14 with value: 246.97655487060547.
[I 2026-10-02 19:06:41,179] Trial 17 finished with value: 250.57922744750977 and parameters: {'n_estimators': 1233, 'learning_rate': 0.14437226040288112, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.7839000352397838, 'colsample_bytree': 0.6195061180822045, 'gamma': 0.9511142124376157, 'reg_alpha': 9.707883000885327e-08, 'reg_lambda': 0.9385377569345077}. Best is trial 14 with value: 246.97655487060547.
[I 2026-10-02 19:06:43,514] Trial 18 finished with value: 261.20685958862305 and parameters: {'n_estimators': 911, 'learning_rate': 0.0650643055629913, 'max_depth': 4, 'min_child_weight': 5, 'subsample': 0.7239173460903348, 'colsample_bytree': 0.7105282865232264, 'gamma': 0.9496044454509593, 'reg_alpha': 9.246947788331926e-06, 'reg_lambda': 4.675016066305415}. Best is trial 14 with value: 246.97655487060547.
[I 2026-10-02 19:06:46,708] Trial 19 finished with value: 265.85892486572266 and parameters: {'n_estimators': 1448, 'learning_rate': 0.1713561313352515, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.6875300711791691, 'colsample_bytree': 0.7223521929873241, 'gamma': 1.044593083020097, 'reg_alpha': 1.857595477333675e-05, 'reg_lambda': 2.2652483060906627}. Best is trial 14 with value: 246.97655487060547.
[I 2026-10-02 19:06:49,687] Trial 20 finished with value: 260.7785415649414 and parameters: {'n_estimators': 1352, 'learning_rate': 0.10990476300645433, 'max_depth': 4, 'min_child_weight': 6, 'subsample': 0.6018233100411357, 'colsample_bytree': 0.7015144776569532, 'gamma': 1.9617558326353817, 'reg_alpha': 1.0175107253601232e-05, 'reg_lambda': 3.24962976391476}. Best is trial 14 with value: 246.97655487060547.
[I 2026-10-02 19:06:51,305] Trial 21 finished with value: 258.7638511657715 and parameters: {'n_estimators': 695, 'learning_rate': 0.10412945980020767, 'max_depth': 4, 'min_child_weight': 1, 'subsample': 0.6046922678110791, 'colsample_bytree': 0.6953295717035982, 'gamma': 1.7397444044675743, 'reg_alpha': 4.131288641516464e-05, 'reg_lambda': 0.5369301458550924}. Best is trial 14 with value: 246.97655487060547.
[I 2026-10-02 19:06:53,811] Trial 22 finished with value: 266.3521308898926 and parameters: {'n_estimators': 1059, 'learning_rate': 0.15249157940490854, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.6110926934875821, 'colsample_bytree': 0.6971791193013993, 'gamma': 0.6749109141474712, 'reg_alpha': 4.596840428976293e-07, 'reg_lambda': 7.6424611055954115}. Best is trial 14 with value: 246.97655487060547.
[I 2026-10-02 19:06:55,520] Trial 23 finished with value: 246.2220573425293 and parameters: {'n_estimators': 907, 'learning_rate': 0.12076408308220424, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.7236402974645328, 'colsample_bytree': 0.6040077790338606, 'gamma': 1.5994451509626266, 'reg_alpha': 5.935832419409782e-07, 'reg_lambda': 3.4055881889044266}. Best is trial 23 with value: 246.2220573425293.
[I 2026-10-02 19:06:58,606] Trial 24 finished with value: 264.10634994506836 and parameters: {'n_estimators': 1146, 'learning_rate': 0.10736697820039307, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.6969215742592966, 'colsample_bytree': 0.6346533962133186, 'gamma': 2.047893247461679, 'reg_alpha': 3.910888869511016e-07, 'reg_lambda': 5.244182856563609}. Best is trial 23 with value: 246.2220573425293.
[I 2026-10-02 19:07:01,018] Trial 25 finished with value: 271.7484550476074 and parameters: {'n_estimators': 734, 'learning_rate': 0.14463249806262016, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.7234710592648239, 'colsample_bytree': 0.6097848801051872, 'gamma': 1.9473299610994594, 'reg_alpha': 6.0753801003696195e-06, 'reg_lambda': 5.179334746063922}. Best is trial 23 with value: 246.2220573425293.
[I 2026-10-02 19:07:02,714] Trial 26 finished with value: 252.26909637451172 and parameters: {'n_estimators': 784, 'learning_rate': 0.19675241422870504, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.7641234669130114, 'colsample_bytree': 0.6176056593111774, 'gamma': 1.5049450777496902, 'reg_alpha': 6.370728182486709e-07, 'reg_lambda': 1.271140148161849}. Best is trial 23 with value: 246.2220573425293.
[I 2026-10-02 19:07:04,604] Trial 27 finished with value: 255.78408432006836 and parameters: {'n_estimators': 941, 'learning_rate': 0.11245774054500902, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.7463456278704141, 'colsample_bytree': 0.6555138608726013, 'gamma': 0.12519938222973281, 'reg_alpha': 6.142123830184178e-06, 'reg_lambda': 1.1786881702260807}. Best is trial 23 with value: 246.2220573425293.
[I 2026-10-02 19:07:06,454] Trial 28 finished with value: 248.77799224853516 and parameters: {'n_estimators': 856, 'learning_rate': 0.1598284797047264, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.6341467280888564, 'colsample_bytree': 0.6875752483498766, 'gamma': 1.2537762631440792, 'reg_alpha': 1.6059657566971848e-05, 'reg_lambda': 1.3926805224781493}. Best is trial 23 with value: 246.2220573425293.
[I 2026-10-02 19:07:09,646] Trial 29 finished with value: 274.0564384460449 and parameters: {'n_estimators': 868, 'learning_rate': 0.11365986207580646, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.6601509184304876, 'colsample_bytree': 0.6647011546272064, 'gamma': 1.9251549339799117, 'reg_alpha': 4.130152732951609e-07, 'reg_lambda': 9.571285443934979}. Best is trial 23 with value: 246.2220573425293.
[I 2026-10-02 19:07:11,812] Trial 30 finished with value: 255.1557846069336 and parameters: {'n_estimators': 1145, 'learning_rate': 0.12065942723440509, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.7447173994026164, 'colsample_bytree': 0.6300657821448069, 'gamma': 1.7449111999064026, 'reg_alpha': 2.42977446342959e-05, 'reg_lambda': 2.188911334775533}. Best is trial 23 with value: 246.2220573425293.
[I 2026-10-02 19:07:14,185] Trial 31 finished with value: 253.1023826599121 and parameters: {'n_estimators': 1263, 'learning_rate': 0.13508506960181962, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.7343881043035108, 'colsample_bytree': 0.6032169663600271, 'gamma': 0.7118199015992671, 'reg_alpha': 7.750236082531735e-08, 'reg_lambda': 1.601720258751951}. Best is trial 23 with value: 246.2220573425293.
[I 2026-10-02 19:07:15,770] Trial 32 finished with value: 260.21863555908203 and parameters: {'n_estimators': 674, 'learning_rate': 0.0877238757721979, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.6894442050512685, 'colsample_bytree': 0.6613701011024665, 'gamma': 1.3968598467200637, 'reg_alpha': 1.812122819560316e-05, 'reg_lambda': 5.812636769987389}. Best is trial 23 with value: 246.2220573425293.
[I 2026-10-02 19:07:17,035] Trial 33 finished with value: 245.67664337158203 and parameters: {'n_estimators': 630, 'learning_rate': 0.14127945276792403, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.6860796351063262, 'colsample_bytree': 0.7348490781363393, 'gamma': 1.0523946503484392, 'reg_alpha': 4.8778142331171976e-06, 'reg_lambda': 1.8940998726084215}. Best is trial 33 with value: 245.67664337158203.
[I 2026-10-02 19:07:18,572] Trial 34 finished with value: 273.5993423461914 and parameters: {'n_estimators': 457, 'learning_rate': 0.16998962787085148, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6948045199506532, 'colsample_bytree': 0.7165229834724745, 'gamma': 0.9001171168822637, 'reg_alpha': 2.7556158709987245e-05, 'reg_lambda': 4.1089518458664696}. Best is trial 33 with value: 245.67664337158203.
[I 2026-10-02 19:07:20,378] Trial 35 finished with value: 247.15304565429688 and parameters: {'n_estimators': 957, 'learning_rate': 0.11487705912014509, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.6712885368541102, 'colsample_bytree': 0.6607220868351434, 'gamma': 2.471597912616375, 'reg_alpha': 1.089559740108513e-06, 'reg_lambda': 0.7342620606891479}. Best is trial 33 with value: 245.67664337158203.
[I 2026-10-02 19:07:22,092] Trial 36 finished with value: 258.7074432373047 and parameters: {'n_estimators': 740, 'learning_rate': 0.11635325909322786, 'max_depth': 4, 'min_child_weight': 4, 'subsample': 0.721046826044316, 'colsample_bytree': 0.6319569901584304, 'gamma': 1.517102932453939, 'reg_alpha': 2.642894619520453e-07, 'reg_lambda': 1.9061374417261627}. Best is trial 33 with value: 245.67664337158203.
[I 2026-10-02 19:07:23,322] Trial 37 finished with value: 249.16682815551758 and parameters: {'n_estimators': 605, 'learning_rate': 0.18584053729382952, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.6933807500544501, 'colsample_bytree': 0.6844521380204349, 'gamma': 1.0789829658843144, 'reg_alpha': 5.302122446952722e-07, 'reg_lambda': 2.310203195021549}. Best is trial 33 with value: 245.67664337158203.
[I 2026-10-02 19:07:24,250] Trial 38 finished with value: 248.85051727294922 and parameters: {'n_estimators': 473, 'learning_rate': 0.1122712696270923, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.6903455372388841, 'colsample_bytree': 0.6983786961982524, 'gamma': 0.8122591749919543, 'reg_alpha': 1.95976133885404e-05, 'reg_lambda': 2.376848112362301}. Best is trial 33 with value: 245.67664337158203.
[I 2026-10-02 19:07:25,858] Trial 39 finished with value: 252.62227630615234 and parameters: {'n_estimators': 871, 'learning_rate': 0.14497111877070173, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.6434386959233678, 'colsample_bytree': 0.6413242100544335, 'gamma': 1.8629849381508485, 'reg_alpha': 6.14143563269591e-05, 'reg_lambda': 1.6239272879646733}. Best is trial 33 with value: 245.67664337158203.
[I 2026-10-02 19:07:27,596] Trial 40 finished with value: 264.05328369140625 and parameters: {'n_estimators': 814, 'learning_rate': 0.10860378852087467, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.6791169919914051, 'colsample_bytree': 0.6041230744121572, 'gamma': 1.32494165707046, 'reg_alpha': 5.543839340092876e-07, 'reg_lambda': 5.5749602998693835}. Best is trial 33 with value: 245.67664337158203.
[I 2026-10-02 19:07:29,991] Trial 41 finished with value: 256.43482208251953 and parameters: {'n_estimators': 1447, 'learning_rate': 0.1410665589937397, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.7531932403209418, 'colsample_bytree': 0.6398111412904706, 'gamma': 1.9597063470145575, 'reg_alpha': 5.317387821161289e-07, 'reg_lambda': 1.1703076210559331}. Best is trial 33 with value: 245.67664337158203.
[I 2026-10-02 19:07:31,966] Trial 42 finished with value: 260.4200744628906 and parameters: {'n_estimators': 929, 'learning_rate': 0.11796647663225696, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.6895302479612285, 'colsample_bytree': 0.6347527149661542, 'gamma': 1.1866947920961017, 'reg_alpha': 1.9987814149602976e-08, 'reg_lambda': 5.737031191057846}. Best is trial 33 with value: 245.67664337158203.
[I 2026-10-02 19:07:32,966] Trial 43 finished with value: 255.34454345703125 and parameters: {'n_estimators': 560, 'learning_rate': 0.10772363122819478, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.6742557181630665, 'colsample_bytree': 0.6372061565999944, 'gamma': 1.5300141072873665, 'reg_alpha': 7.826496045275661e-07, 'reg_lambda': 3.2188667672652036}. Best is trial 33 with value: 245.67664337158203.
[I 2026-10-02 19:07:34,664] Trial 44 finished with value: 256.7766304016113 and parameters: {'n_estimators': 908, 'learning_rate': 0.15081089671427478, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.6720523864704957, 'colsample_bytree': 0.6283043715402336, 'gamma': 1.7332925095494387, 'reg_alpha': 5.096718206489896e-07, 'reg_lambda': 2.622044563964164}. Best is trial 33 with value: 245.67664337158203.
[I 2026-10-02 19:07:36,472] Trial 45 finished with value: 255.20273971557617 and parameters: {'n_estimators': 966, 'learning_rate': 0.14655227586113645, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.7522227214435541, 'colsample_bytree': 0.6016764981286782, 'gamma': 2.6280425003981014, 'reg_alpha': 6.320301940203952e-06, 'reg_lambda': 1.8661326157430995}. Best is trial 33 with value: 245.67664337158203.
[I 2026-10-02 19:07:37,993] Trial 46 finished with value: 252.20196914672852 and parameters: {'n_estimators': 835, 'learning_rate': 0.1014828590025292, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.734036058634358, 'colsample_bytree': 0.6250871142336126, 'gamma': 1.7640451818564409, 'reg_alpha': 2.749362115903264e-07, 'reg_lambda': 6.671595612873675}. Best is trial 33 with value: 245.67664337158203.
[I 2026-10-02 19:07:39,663] Trial 47 finished with value: 248.83837509155273 and parameters: {'n_estimators': 887, 'learning_rate': 0.123824435538884, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.7219599922549748, 'colsample_bytree': 0.6689381527806386, 'gamma': 1.0843662994836676, 'reg_alpha': 1.5382710834727026e-06, 'reg_lambda': 1.1620857960257562}. Best is trial 33 with value: 245.67664337158203.

In [8]:
print("Best CV RMSE:")
print(study.best_value)

print("\nBest parameters:")

for param, value in study.best_params.items():
    print(f"{param}: {value}")

Best CV RMSE:
245.67664337158203

Best parameters:
n_estimators: 630
learning_rate: 0.14127945276792403
max_depth: 3
min_child_weight: 3
subsample: 0.6860796351063262
colsample_bytree: 0.7348490781363393
gamma: 1.0523946503484392
reg_alpha: 4.8778142331171976e-06
reg_lambda: 1.8940998726084215

In [9]:
best_params = study.best_params

seeds = [0, 1, 2, 3, 42]

results = []

for seed in seeds:

    model = xgb.XGBRegressor(
        **best_params,
        objective="reg:squarederror",
        random_state=seed,
        n_jobs=-1
    )

    model.fit(
        X_train,
        y_train
    )

    y_pred = model.predict(X_val)

    results.append({
        "Seed": seed,
        "RMSE": root_mean_squared_error(y_val, y_pred),
        "MSE": mean_squared_error(y_val, y_pred),
        "MAE": mean_absolute_error(y_val, y_pred),
        "MAPE": mean_absolute_percentage_error(y_val, y_pred),
        "R2": r2_score(y_val, y_pred)
    })

stability_df = pd.DataFrame(results)

stability_summary = stability_df.drop(
    columns="Seed"
).agg(["mean", "std", "min", "max"]).T

print("=== Results by seed ===")
display(stability_df)

print("\n=== Stability summary ===")
display(stability_summary)

=== Results by seed ===

   Seed        RMSE           MSE         MAE      MAPE        R2
0     0  155.215622  24091.888672  114.367210  0.053766  0.854173
1     1  153.471359  23553.457031  112.982391  0.053243  0.857432
2     2  153.910370  23688.402344  113.351936  0.053365  0.856615
3     3  155.346558  24132.550781  114.260727  0.053940  0.853927
4    42  152.568451  23277.130859  112.387375  0.053109  0.859105

=== Stability summary ===

              mean         std           min           max
RMSE    154.102472    1.180601    152.568451    155.346558
MSE   23748.685937  363.748871  23277.130859  24132.550781
MAE     113.469928    0.844691    112.387375    114.367210
MAPE      0.053484    0.000354      0.053109      0.053940
R2        0.856250    0.002202      0.853927      0.859105

In [10]:
stability_df.to_csv("../report/seed_delta24_temp_ghi_val_report.csv", index = False)
stability_summary.to_csv("../report/seed_summary_delta24_temp_ghi_val_report.csv", index = False)

# 4. Final Training on year 1 and year 2

In [11]:
df_train, df_test = build_features(
                                df_train = pd.read_excel("../Dataset/training.xlsx"), 
                                df_test = pd.read_excel("../Dataset/testing.xlsx")
                                   )

In [12]:
X_train = df_train[features]
y_train = df_train[target]

X_test = df_test[features]

In [13]:
print("Dataset sizes:")
print(f"Train (Year 1): {len(X_train):,}")
print(f"Validation (Year 2): {len(X_val):,}")
print(f"Test (Year 3): {len(X_test):,}")

Dataset sizes:
Train (Year 1): 17,544
Validation (Year 2): 8,760
Test (Year 3): 8,760

In [14]:
seeds = [0, 1, 2, 3, 42]

test_predictions = []

for seed in seeds:

    model = xgb.XGBRegressor(
        **best_params,
        objective="reg:squarederror",
        random_state=seed,
        n_jobs=-1
    )

    model.fit(
        X_train,
        y_train
    )

    pred = model.predict(X_test)

    test_predictions.append(pred)

y_test_pred = np.mean(
    test_predictions,
    axis=0
)

In [15]:
pd.DataFrame(y_test_pred).to_csv("../report/delta24_temp_ghi_test_prediction.csv", index = False)